<?php

namespace Database\Seeders;

use App\Models\kategori;
use App\Models\Produk;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use RuntimeException;

class EmblemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        /*
         * Seeder ini menganggap KategoriSeeder sudah dijalankan lebih dulu
         * dan kategori "Emblem" sudah tersedia.
         *
         * Jika nama kolom kategori Anda bukan `nama_kategori`,
         * sesuaikan query di bawah ini.
         */
        $kategori = kategori::where('nama_kategori', 'EMBLEM')->first();

        if (! $kategori) {
            throw new RuntimeException(
                'Kategori Emblem tidak ditemukan. Jalankan KategoriSeeder terlebih dahulu.'
            );
        }

        $data = [
            ['sku' => 'EMB0001', 'nama_produk' => 'LOGO ONE PIECE', 'variasi' => '-', 'hpp' => 9000],
            ['sku' => 'EMB0002', 'nama_produk' => 'HASIL KERJA KERAS', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0003', 'nama_produk' => 'HASIL KERJA KERAS', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0004', 'nama_produk' => 'HASIL KERJA KERAS', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0005', 'nama_produk' => 'HASIL KERJA KERAS', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0006', 'nama_produk' => 'HASIL KERJA KERAS', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0007', 'nama_produk' => 'HASIL KERJA KERAS', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0008', 'nama_produk' => 'HASIL KERJA KERAS', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0009', 'nama_produk' => 'SCOOPY DEVIL', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0010', 'nama_produk' => 'SCOOPY DEVIL', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0011', 'nama_produk' => 'SCOOPY DEVIL', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0012', 'nama_produk' => 'SCOOPY DEVIL', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0013', 'nama_produk' => 'SCOOPY DEVIL', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0014', 'nama_produk' => 'SCOOPY DEVIL', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0015', 'nama_produk' => 'SCOOPY DEVIL', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0016', 'nama_produk' => 'TRD SPORTIVO', 'variasi' => '-', 'hpp' => 9000],
            ['sku' => 'EMB0017', 'nama_produk' => 'SCOOPY GEMOY', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0018', 'nama_produk' => 'SCOOPY GEMOY', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0019', 'nama_produk' => 'SCOOPY GEMOY', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0020', 'nama_produk' => 'SCOOPY GEMOY', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0021', 'nama_produk' => 'SCOOPY GEMOY', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0022', 'nama_produk' => 'SCOOPY GEMOY', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0023', 'nama_produk' => 'SCOOPY GEMOY', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0024', 'nama_produk' => 'SUPRA X 125R', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0025', 'nama_produk' => 'SUPRA X 125R', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0026', 'nama_produk' => 'SUPRA X 125R', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0027', 'nama_produk' => 'SUPRA X 125R', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0028', 'nama_produk' => 'SUPRA X 125R', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0029', 'nama_produk' => 'SUPRA X 125R', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0030', 'nama_produk' => 'SUPRA X 125R', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0031', 'nama_produk' => 'JAGA JARAK', 'variasi' => '-', 'hpp' => 9000],
            ['sku' => 'EMB0032', 'nama_produk' => 'NMAX GANTENG', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0033', 'nama_produk' => 'NMAX GANTENG', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0034', 'nama_produk' => 'NMAX GANTENG', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0035', 'nama_produk' => 'NMAX GANTENG', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0036', 'nama_produk' => 'NMAX GANTENG', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0037', 'nama_produk' => 'NMAX GANTENG', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0038', 'nama_produk' => 'NMAX GANTENG', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0039', 'nama_produk' => 'INDONESIA LOGO', 'variasi' => '-', 'hpp' => 16000],
            ['sku' => 'EMB0040', 'nama_produk' => 'PCX 160', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0041', 'nama_produk' => 'PCX 160', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0042', 'nama_produk' => 'PCX 160', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0043', 'nama_produk' => 'PCX 160', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0044', 'nama_produk' => 'PCX 160', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0045', 'nama_produk' => 'PCX 160', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0046', 'nama_produk' => 'PCX 160', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0047', 'nama_produk' => 'BEAT GANTENG', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0048', 'nama_produk' => 'BEAT GANTENG', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0049', 'nama_produk' => 'BEAT GANTENG', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0050', 'nama_produk' => 'BEAT GANTENG', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0051', 'nama_produk' => 'BEAT GANTENG', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0052', 'nama_produk' => 'BEAT GANTENG', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0053', 'nama_produk' => 'BEAT GANTENG', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0054', 'nama_produk' => 'HONDA SAYAP', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0055', 'nama_produk' => 'HONDA SAYAP', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0056', 'nama_produk' => 'HONDA SAYAP', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0057', 'nama_produk' => 'HONDA SAYAP', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0058', 'nama_produk' => 'HONDA SAYAP', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0059', 'nama_produk' => 'HONDA SAYAP', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0060', 'nama_produk' => 'HONDA SAYAP', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0061', 'nama_produk' => 'HOTWHEELS', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0062', 'nama_produk' => 'HOTWHEELS', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0063', 'nama_produk' => 'HOTWHEELS', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0064', 'nama_produk' => 'HOTWHEELS', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0065', 'nama_produk' => 'HOTWHEELS', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0066', 'nama_produk' => 'HOTWHEELS', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0067', 'nama_produk' => 'HOTWHEELS', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0068', 'nama_produk' => 'SATRIA F150', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0069', 'nama_produk' => 'SATRIA F150', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0070', 'nama_produk' => 'SATRIA F150', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0071', 'nama_produk' => 'SATRIA F150', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0072', 'nama_produk' => 'SATRIA F150', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0073', 'nama_produk' => 'SATRIA F150', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0074', 'nama_produk' => 'SATRIA F150', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0075', 'nama_produk' => 'ADV 160', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0076', 'nama_produk' => 'ADV 160', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0077', 'nama_produk' => 'ADV 160', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0078', 'nama_produk' => 'ADV 160', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0079', 'nama_produk' => 'ADV 160', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0080', 'nama_produk' => 'ADV 160', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0081', 'nama_produk' => 'ADV 160', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0082', 'nama_produk' => 'ALFA', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0083', 'nama_produk' => 'ALFA', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0084', 'nama_produk' => 'ALFA', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0085', 'nama_produk' => 'ALFA', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0086', 'nama_produk' => 'ALFA', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0087', 'nama_produk' => 'ALFA', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0088', 'nama_produk' => 'ALFA', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0089', 'nama_produk' => 'BACOT', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0090', 'nama_produk' => 'BACOT', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0091', 'nama_produk' => 'BACOT', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0092', 'nama_produk' => 'BACOT', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0093', 'nama_produk' => 'BACOT', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0094', 'nama_produk' => 'BACOT', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0095', 'nama_produk' => 'BACOT', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0096', 'nama_produk' => 'BATOK 160', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0097', 'nama_produk' => 'BATOK 160', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0098', 'nama_produk' => 'BATOK 160', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0099', 'nama_produk' => 'BATOK 160', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0100', 'nama_produk' => 'BATOK 160', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0101', 'nama_produk' => 'BATOK 160', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0102', 'nama_produk' => 'BATOK 160', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0103', 'nama_produk' => 'BEAT', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0104', 'nama_produk' => 'BEAT', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0105', 'nama_produk' => 'BEAT', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0106', 'nama_produk' => 'BEAT', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0107', 'nama_produk' => 'BEAT', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0108', 'nama_produk' => 'BEAT', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0109', 'nama_produk' => 'BEAT', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0110', 'nama_produk' => 'BEAT JAPAN', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0111', 'nama_produk' => 'BEAT JAPAN', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0112', 'nama_produk' => 'BEAT JAPAN', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0113', 'nama_produk' => 'BEAT JAPAN', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0114', 'nama_produk' => 'BEAT JAPAN', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0115', 'nama_produk' => 'BEAT JAPAN', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0116', 'nama_produk' => 'BEAT JAPAN', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0117', 'nama_produk' => 'BEAT MATIC', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0118', 'nama_produk' => 'BEAT MATIC', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0119', 'nama_produk' => 'BEAT MATIC', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0120', 'nama_produk' => 'BEAT MATIC', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0121', 'nama_produk' => 'BEAT MATIC', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0122', 'nama_produk' => 'BEAT MATIC', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0123', 'nama_produk' => 'BEAT MATIC', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0124', 'nama_produk' => 'BEAT PELAN', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0125', 'nama_produk' => 'BEAT PELAN', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0126', 'nama_produk' => 'BEAT PELAN', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0127', 'nama_produk' => 'BEAT PELAN', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0128', 'nama_produk' => 'BEAT PELAN', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0129', 'nama_produk' => 'BEAT PELAN', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0130', 'nama_produk' => 'BEAT PELAN', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0131', 'nama_produk' => 'BEAT STREET', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0132', 'nama_produk' => 'BEAT STREET', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0133', 'nama_produk' => 'BEAT STREET', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0134', 'nama_produk' => 'BEAT STREET', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0135', 'nama_produk' => 'BEAT STREET', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0136', 'nama_produk' => 'BEAT STREET', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0137', 'nama_produk' => 'BEAT STREET', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0138', 'nama_produk' => 'BISMILLAH', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0139', 'nama_produk' => 'BISMILLAH', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0140', 'nama_produk' => 'BISMILLAH', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0141', 'nama_produk' => 'BISMILLAH', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0142', 'nama_produk' => 'BISMILLAH', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0143', 'nama_produk' => 'BISMILLAH', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0144', 'nama_produk' => 'BISMILLAH', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0145', 'nama_produk' => 'CLASSIC C70', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0146', 'nama_produk' => 'CLASSIC C70', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0147', 'nama_produk' => 'CLASSIC C70', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0148', 'nama_produk' => 'CLASSIC C70', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0149', 'nama_produk' => 'CLASSIC C70', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0150', 'nama_produk' => 'CLASSIC C70', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0151', 'nama_produk' => 'CLASSIC C70', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0152', 'nama_produk' => 'CLICK', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0153', 'nama_produk' => 'CLICK', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0154', 'nama_produk' => 'CLICK', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0155', 'nama_produk' => 'CLICK', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0156', 'nama_produk' => 'CLICK', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0157', 'nama_produk' => 'CLICK', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0158', 'nama_produk' => 'CLICK', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0159', 'nama_produk' => 'DECEPTICON', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0160', 'nama_produk' => 'DECEPTICON', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0161', 'nama_produk' => 'DECEPTICON', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0162', 'nama_produk' => 'DECEPTICON', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0163', 'nama_produk' => 'DECEPTICON', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0164', 'nama_produk' => 'DECEPTICON', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0165', 'nama_produk' => 'DECEPTICON', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0166', 'nama_produk' => 'HASIL NGEPET', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0167', 'nama_produk' => 'HASIL NGEPET', 'variasi' => 'SILVER-MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0168', 'nama_produk' => 'HASIL NGEPET', 'variasi' => 'MERAH-SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0169', 'nama_produk' => 'HASIL NGEPET', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0170', 'nama_produk' => 'HASIL NGEPET', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0171', 'nama_produk' => 'HASIL NGEPET', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0172', 'nama_produk' => 'HASIL NGEPET', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0173', 'nama_produk' => 'HONDA 10CM', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0174', 'nama_produk' => 'HONDA 10CM', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0175', 'nama_produk' => 'HONDA 10CM', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0176', 'nama_produk' => 'HONDA 10CM', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0177', 'nama_produk' => 'HONDA 10CM', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0178', 'nama_produk' => 'HONDA 10CM', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0179', 'nama_produk' => 'HONDA 10CM', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0180', 'nama_produk' => 'HONDA 15CM', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0181', 'nama_produk' => 'HONDA 15CM', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0182', 'nama_produk' => 'HONDA 15CM', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0183', 'nama_produk' => 'HONDA 15CM', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0184', 'nama_produk' => 'HONDA 15CM', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0185', 'nama_produk' => 'HONDA 15CM', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0186', 'nama_produk' => 'HONDA 15CM', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0187', 'nama_produk' => 'LIMITED LATIN', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0188', 'nama_produk' => 'LIMITED LATIN', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0189', 'nama_produk' => 'LIMITED LATIN', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0190', 'nama_produk' => 'LIMITED LATIN', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0191', 'nama_produk' => 'LIMITED LATIN', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0192', 'nama_produk' => 'LIMITED LATIN', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0193', 'nama_produk' => 'LIMITED LATIN', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0194', 'nama_produk' => 'MATERNAL TULISAN', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0195', 'nama_produk' => 'MATERNAL TULISAN', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0196', 'nama_produk' => 'MATERNAL TULISAN', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0197', 'nama_produk' => 'MATERNAL TULISAN', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0198', 'nama_produk' => 'MATERNAL TULISAN', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0199', 'nama_produk' => 'MATERNAL TULISAN', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0200', 'nama_produk' => 'MATERNAL TULISAN', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0201', 'nama_produk' => 'MATERNAL LOGO', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0202', 'nama_produk' => 'MATERNAL LOGO', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0203', 'nama_produk' => 'MATERNAL LOGO', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0204', 'nama_produk' => 'MATERNAL LOGO', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0205', 'nama_produk' => 'MATERNAL LOGO', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0206', 'nama_produk' => 'MATERNAL LOGO', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0207', 'nama_produk' => 'MATERNAL LOGO', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0208', 'nama_produk' => 'MAXI SIGNATURE', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0209', 'nama_produk' => 'MAXI SIGNATURE', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0210', 'nama_produk' => 'MAXI SIGNATURE', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0211', 'nama_produk' => 'MAXI SIGNATURE', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0212', 'nama_produk' => 'MAXI SIGNATURE', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0213', 'nama_produk' => 'MAXI SIGNATURE', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0214', 'nama_produk' => 'MAXI SIGNATURE', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0215', 'nama_produk' => 'MIO', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0216', 'nama_produk' => 'MIO', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0217', 'nama_produk' => 'MIO', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0218', 'nama_produk' => 'MIO', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0219', 'nama_produk' => 'MIO', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0220', 'nama_produk' => 'MIO', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0221', 'nama_produk' => 'MIO', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0222', 'nama_produk' => 'MIO JAPAN', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0223', 'nama_produk' => 'MIO JAPAN', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0224', 'nama_produk' => 'MIO JAPAN', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0225', 'nama_produk' => 'MIO JAPAN', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0226', 'nama_produk' => 'MIO JAPAN', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0227', 'nama_produk' => 'MIO JAPAN', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0228', 'nama_produk' => 'MIO JAPAN', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0229', 'nama_produk' => 'NMAX', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0230', 'nama_produk' => 'NMAX', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0231', 'nama_produk' => 'NMAX', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0232', 'nama_produk' => 'NMAX', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0233', 'nama_produk' => 'NMAX', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0234', 'nama_produk' => 'NMAX', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0235', 'nama_produk' => 'NMAX', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0236', 'nama_produk' => 'REVO', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0237', 'nama_produk' => 'REVO', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0238', 'nama_produk' => 'REVO', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0239', 'nama_produk' => 'REVO', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0240', 'nama_produk' => 'REVO', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0241', 'nama_produk' => 'REVO', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0242', 'nama_produk' => 'REVO', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0243', 'nama_produk' => 'SATSET', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0244', 'nama_produk' => 'SATSET', 'variasi' => 'MERAH SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0245', 'nama_produk' => 'SATSET', 'variasi' => 'SILVER MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0246', 'nama_produk' => 'SATSET', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0247', 'nama_produk' => 'SATSET', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0248', 'nama_produk' => 'SATSET', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0249', 'nama_produk' => 'SATSET', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0250', 'nama_produk' => 'SCOOPY LATIN', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0251', 'nama_produk' => 'SCOOPY LATIN', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0252', 'nama_produk' => 'SCOOPY LATIN', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0253', 'nama_produk' => 'SCOOPY LATIN', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0254', 'nama_produk' => 'SCOOPY LATIN', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0255', 'nama_produk' => 'SCOOPY LATIN', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0256', 'nama_produk' => 'SCOOPY LATIN', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0257', 'nama_produk' => 'TAKUT BECEK', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0258', 'nama_produk' => 'TAKUT BECEK', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0259', 'nama_produk' => 'TAKUT BECEK', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0260', 'nama_produk' => 'TAKUT BECEK', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0261', 'nama_produk' => 'TAKUT BECEK', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0262', 'nama_produk' => 'TAKUT BECEK', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0263', 'nama_produk' => 'TAKUT BECEK', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0264', 'nama_produk' => 'VARIO', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0265', 'nama_produk' => 'VARIO', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0266', 'nama_produk' => 'VARIO', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0267', 'nama_produk' => 'VARIO', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0268', 'nama_produk' => 'VARIO', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0269', 'nama_produk' => 'VARIO', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0270', 'nama_produk' => 'VARIO', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0271', 'nama_produk' => 'VARIO GANTENG', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0272', 'nama_produk' => 'VARIO GANTENG', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0273', 'nama_produk' => 'VARIO GANTENG', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0274', 'nama_produk' => 'VARIO GANTENG', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0275', 'nama_produk' => 'VARIO GANTENG', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0276', 'nama_produk' => 'VARIO GANTENG', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0277', 'nama_produk' => 'VARIO GANTENG', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0278', 'nama_produk' => 'VARIO JAPAN', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0279', 'nama_produk' => 'VARIO JAPAN', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0280', 'nama_produk' => 'VARIO JAPAN', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0281', 'nama_produk' => 'VARIO JAPAN', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0282', 'nama_produk' => 'VARIO JAPAN', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0283', 'nama_produk' => 'VARIO JAPAN', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0284', 'nama_produk' => 'VARIO JAPAN', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0285', 'nama_produk' => 'VEGA R NEW', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0286', 'nama_produk' => 'VEGA R NEW', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0287', 'nama_produk' => 'VEGA R NEW', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0288', 'nama_produk' => 'VEGA R NEW', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0289', 'nama_produk' => 'VEGA R NEW', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0290', 'nama_produk' => 'VEGA R NEW', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0291', 'nama_produk' => 'VEGA R NEW', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0292', 'nama_produk' => 'VEGA R OLD', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0293', 'nama_produk' => 'VEGA R OLD', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0294', 'nama_produk' => 'VEGA R OLD', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0295', 'nama_produk' => 'VEGA R OLD', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0296', 'nama_produk' => 'VEGA R OLD', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0297', 'nama_produk' => 'VEGA R OLD', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0298', 'nama_produk' => 'VEGA R OLD', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0299', 'nama_produk' => 'XEON NEW 125', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0300', 'nama_produk' => 'XEON NEW 125', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0301', 'nama_produk' => 'XEON NEW 125', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0302', 'nama_produk' => 'XEON NEW 125', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0303', 'nama_produk' => 'XEON NEW 125', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0304', 'nama_produk' => 'XEON NEW 125', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0305', 'nama_produk' => 'XEON NEW 125', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0306', 'nama_produk' => 'XEON OLD', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0307', 'nama_produk' => 'XEON OLD', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0308', 'nama_produk' => 'XEON OLD', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0309', 'nama_produk' => 'XEON OLD', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0310', 'nama_produk' => 'XEON OLD', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0311', 'nama_produk' => 'XEON OLD', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0312', 'nama_produk' => 'XEON OLD', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0313', 'nama_produk' => 'XMAX', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0314', 'nama_produk' => 'XMAX', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0315', 'nama_produk' => 'XMAX', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0316', 'nama_produk' => 'XMAX', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0317', 'nama_produk' => 'XMAX', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0318', 'nama_produk' => 'XMAX', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0319', 'nama_produk' => 'XMAX', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0320', 'nama_produk' => 'XRIDE', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0321', 'nama_produk' => 'XRIDE', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0322', 'nama_produk' => 'XRIDE', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0323', 'nama_produk' => 'XRIDE', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0324', 'nama_produk' => 'XRIDE', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0325', 'nama_produk' => 'XRIDE', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0326', 'nama_produk' => 'XRIDE', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0327', 'nama_produk' => 'VIXION', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0328', 'nama_produk' => 'VIXION', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0329', 'nama_produk' => 'VIXION', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0330', 'nama_produk' => 'VIXION', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0331', 'nama_produk' => 'VIXION', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0332', 'nama_produk' => 'VIXION', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0333', 'nama_produk' => 'VIXION', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0334', 'nama_produk' => 'AEROX', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0335', 'nama_produk' => 'AEROX', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0336', 'nama_produk' => 'AEROX', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0337', 'nama_produk' => 'AEROX', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0338', 'nama_produk' => 'AEROX', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0339', 'nama_produk' => 'AEROX', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0340', 'nama_produk' => 'AEROX', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0341', 'nama_produk' => 'MENYALA ABANGKU', 'variasi' => '-', 'hpp' => 9000],
            ['sku' => 'EMB0342', 'nama_produk' => 'YAMAHA SMILE', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0343', 'nama_produk' => 'YAMAHA SMILE', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0344', 'nama_produk' => 'YAMAHA SMILE', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0345', 'nama_produk' => 'YAMAHA SMILE', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0346', 'nama_produk' => 'YAMAHA SMILE', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0347', 'nama_produk' => 'YAMAHA SMILE', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0348', 'nama_produk' => 'YAMAHA SMILE', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0349', 'nama_produk' => 'ELEK TAPI GAK KREDIT', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0350', 'nama_produk' => 'ELEK TAPI GAK KREDIT', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0351', 'nama_produk' => 'ELEK TAPI GAK KREDIT', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0352', 'nama_produk' => 'ELEK TAPI GAK KREDIT', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0353', 'nama_produk' => 'ELEK TAPI GAK KREDIT', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0354', 'nama_produk' => 'ELEK TAPI GAK KREDIT', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0355', 'nama_produk' => 'ELEK TAPI GAK KREDIT', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0356', 'nama_produk' => 'LOGO APPLE IPHONE', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0357', 'nama_produk' => 'LOGO APPLE IPHONE', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0358', 'nama_produk' => 'LOGO APPLE IPHONE', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0359', 'nama_produk' => 'LOGO APPLE IPHONE', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0360', 'nama_produk' => 'LOGO APPLE IPHONE', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0361', 'nama_produk' => 'LOGO APPLE IPHONE', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0362', 'nama_produk' => 'LOGO APPLE IPHONE', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0363', 'nama_produk' => 'TAMIYA', 'variasi' => '-', 'hpp' => 9000],
            ['sku' => 'EMB0364', 'nama_produk' => 'MOKONDO GANK', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0365', 'nama_produk' => 'MOKONDO GANK', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0366', 'nama_produk' => 'MOKONDO GANK', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0367', 'nama_produk' => 'MOKONDO GANK', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0368', 'nama_produk' => 'MOKONDO GANK', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0369', 'nama_produk' => 'MOKONDO GANK', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0370', 'nama_produk' => 'MOKONDO GANK', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0371', 'nama_produk' => 'ELEK TAPI GK WARISAN', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0372', 'nama_produk' => 'ELEK TAPI GK WARISAN', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0373', 'nama_produk' => 'ELEK TAPI GK WARISAN', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0374', 'nama_produk' => 'ELEK TAPI GK WARISAN', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0375', 'nama_produk' => 'ELEK TAPI GK WARISAN', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0376', 'nama_produk' => 'ELEK TAPI GK WARISAN', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0377', 'nama_produk' => 'ELEK TAPI GK WARISAN', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0378', 'nama_produk' => 'PAUS DARAT', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0379', 'nama_produk' => 'PAUS DARAT', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0380', 'nama_produk' => 'PAUS DARAT', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0381', 'nama_produk' => 'PAUS DARAT', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0382', 'nama_produk' => 'PAUS DARAT', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0383', 'nama_produk' => 'PAUS DARAT', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0384', 'nama_produk' => 'PAUS DARAT', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0385', 'nama_produk' => 'LOW BUDGET', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0386', 'nama_produk' => 'LOW BUDGET', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0387', 'nama_produk' => 'LOW BUDGET', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0388', 'nama_produk' => 'LOW BUDGET', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0389', 'nama_produk' => 'LOW BUDGET', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0390', 'nama_produk' => 'LOW BUDGET', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0391', 'nama_produk' => 'LOW BUDGET', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0392', 'nama_produk' => 'ONE PIECE V2', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0393', 'nama_produk' => 'ONE PIECE V2', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0394', 'nama_produk' => 'ONE PIECE V2', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0395', 'nama_produk' => 'ONE PIECE V2', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0396', 'nama_produk' => 'ONE PIECE V2', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0397', 'nama_produk' => 'ONE PIECE V2', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0398', 'nama_produk' => 'ONE PIECE V2', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0399', 'nama_produk' => 'KALAH PENAMPILAN', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0400', 'nama_produk' => 'KALAH PENAMPILAN', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0401', 'nama_produk' => 'KALAH PENAMPILAN', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0402', 'nama_produk' => 'KALAH PENAMPILAN', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0403', 'nama_produk' => 'KALAH PENAMPILAN', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0404', 'nama_produk' => 'KALAH PENAMPILAN', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0405', 'nama_produk' => 'KALAH PENAMPILAN', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0406', 'nama_produk' => 'INAA MA\'AL USRI YUSRO', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0407', 'nama_produk' => 'INAA MA\'AL USRI YUSRO', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0408', 'nama_produk' => 'INAA MA\'AL USRI YUSRO', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0409', 'nama_produk' => 'INAA MA\'AL USRI YUSRO', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0410', 'nama_produk' => 'INAA MA\'AL USRI YUSRO', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0411', 'nama_produk' => 'INAA MA\'AL USRI YUSRO', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0412', 'nama_produk' => 'INAA MA\'AL USRI YUSRO', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0413', 'nama_produk' => 'HASIL DOA IBU & ISTRI', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0414', 'nama_produk' => 'HASIL DOA IBU & ISTRI', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0415', 'nama_produk' => 'HASIL DOA IBU & ISTRI', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0416', 'nama_produk' => 'HASIL DOA IBU & ISTRI', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0417', 'nama_produk' => 'HASIL DOA IBU & ISTRI', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0418', 'nama_produk' => 'HASIL DOA IBU & ISTRI', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0419', 'nama_produk' => 'HASIL DOA IBU & ISTRI', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0420', 'nama_produk' => 'VARIO CLICK 160', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0421', 'nama_produk' => 'VARIO CLICK 160', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0422', 'nama_produk' => 'VARIO CLICK 160', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0423', 'nama_produk' => 'VARIO CLICK 160', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0424', 'nama_produk' => 'VARIO CLICK 160', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0425', 'nama_produk' => 'VARIO CLICK 160', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0426', 'nama_produk' => 'VARIO CLICK 160', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0427', 'nama_produk' => 'BISMILLAH SETIAP WAKTU', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0428', 'nama_produk' => 'BISMILLAH SETIAP WAKTU', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0429', 'nama_produk' => 'BISMILLAH SETIAP WAKTU', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0430', 'nama_produk' => 'BISMILLAH SETIAP WAKTU', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0431', 'nama_produk' => 'BISMILLAH SETIAP WAKTU', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0432', 'nama_produk' => 'BISMILLAH SETIAP WAKTU', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0433', 'nama_produk' => 'BISMILLAH SETIAP WAKTU', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0434', 'nama_produk' => 'WONG LIYO NGERTI OPO', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0435', 'nama_produk' => 'WONG LIYO NGERTI OPO', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0436', 'nama_produk' => 'WONG LIYO NGERTI OPO', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0437', 'nama_produk' => 'WONG LIYO NGERTI OPO', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0438', 'nama_produk' => 'WONG LIYO NGERTI OPO', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0439', 'nama_produk' => 'WONG LIYO NGERTI OPO', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0440', 'nama_produk' => 'WONG LIYO NGERTI OPO', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0441', 'nama_produk' => 'MIO SOUL NEW', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0442', 'nama_produk' => 'MIO SOUL NEW', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0443', 'nama_produk' => 'MIO SOUL NEW', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0444', 'nama_produk' => 'MIO SOUL NEW', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0445', 'nama_produk' => 'MIO SOUL NEW', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0446', 'nama_produk' => 'MIO SOUL NEW', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0447', 'nama_produk' => 'MIO SOUL NEW', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0448', 'nama_produk' => 'TIMBANG KUDANAN', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0449', 'nama_produk' => 'TIMBANG KUDANAN', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0450', 'nama_produk' => 'TIMBANG KUDANAN', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0451', 'nama_produk' => 'TIMBANG KUDANAN', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0452', 'nama_produk' => 'TIMBANG KUDANAN', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0453', 'nama_produk' => 'TIMBANG KUDANAN', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0454', 'nama_produk' => 'TIMBANG KUDANAN', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0455', 'nama_produk' => 'NYENYENYE', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0456', 'nama_produk' => 'NYENYENYE', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0457', 'nama_produk' => 'NYENYENYE', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0458', 'nama_produk' => 'NYENYENYE', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0459', 'nama_produk' => 'NYENYENYE', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0460', 'nama_produk' => 'NYENYENYE', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0461', 'nama_produk' => 'NYENYENYE', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0462', 'nama_produk' => 'SPECIAL EDITION', 'variasi' => '-', 'hpp' => 9000],
            ['sku' => 'EMB0463', 'nama_produk' => 'SUPRA BAPAK', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0464', 'nama_produk' => 'SUPRA BAPAK', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0465', 'nama_produk' => 'SUPRA BAPAK', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0466', 'nama_produk' => 'SUPRA BAPAK', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0467', 'nama_produk' => 'SUPRA BAPAK', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0468', 'nama_produk' => 'SUPRA BAPAK', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0469', 'nama_produk' => 'SUPRA BAPAK', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0470', 'nama_produk' => 'NINJA', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0471', 'nama_produk' => 'NINJA', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0472', 'nama_produk' => 'NINJA', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0473', 'nama_produk' => 'NINJA', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0474', 'nama_produk' => 'NINJA', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0475', 'nama_produk' => 'NINJA', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0476', 'nama_produk' => 'NINJA', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0477', 'nama_produk' => 'TULISAN ONE PIECE', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0478', 'nama_produk' => 'TULISAN ONE PIECE', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0479', 'nama_produk' => 'TULISAN ONE PIECE', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0480', 'nama_produk' => 'TULISAN ONE PIECE', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0481', 'nama_produk' => 'TULISAN ONE PIECE', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0482', 'nama_produk' => 'TULISAN ONE PIECE', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0483', 'nama_produk' => 'TULISAN ONE PIECE', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0484', 'nama_produk' => 'JUPITER MX', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0485', 'nama_produk' => 'JUPITER MX', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0486', 'nama_produk' => 'JUPITER MX', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0487', 'nama_produk' => 'JUPITER MX', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0488', 'nama_produk' => 'JUPITER MX', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0489', 'nama_produk' => 'JUPITER MX', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0490', 'nama_produk' => 'JUPITER MX', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0491', 'nama_produk' => 'YAMAHA R15M', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0492', 'nama_produk' => 'YAMAHA R15M', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0493', 'nama_produk' => 'YAMAHA R15M', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0494', 'nama_produk' => 'YAMAHA R15M', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0495', 'nama_produk' => 'YAMAHA R15M', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0496', 'nama_produk' => 'YAMAHA R15M', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0497', 'nama_produk' => 'YAMAHA R15M', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0498', 'nama_produk' => 'KARISMA X 125D', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0499', 'nama_produk' => 'KARISMA X 125D', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0500', 'nama_produk' => 'KARISMA X 125D', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0501', 'nama_produk' => 'KARISMA X 125D', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0502', 'nama_produk' => 'KARISMA X 125D', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0503', 'nama_produk' => 'KARISMA X 125D', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0504', 'nama_produk' => 'KARISMA X 125D', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0505', 'nama_produk' => '2 STROKE', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0506', 'nama_produk' => '2 STROKE', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0507', 'nama_produk' => '2 STROKE', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0508', 'nama_produk' => '2 STROKE', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0509', 'nama_produk' => '2 STROKE', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0510', 'nama_produk' => '2 STROKE', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0511', 'nama_produk' => '2 STROKE', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0512', 'nama_produk' => 'DOA ISTRI', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0513', 'nama_produk' => 'DOA ISTRI', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0514', 'nama_produk' => 'DOA ISTRI', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0515', 'nama_produk' => 'DOA ISTRI', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0516', 'nama_produk' => 'DOA ISTRI', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0517', 'nama_produk' => 'DOA ISTRI', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0518', 'nama_produk' => 'DOA ISTRI', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0519', 'nama_produk' => 'Garputala Yamaha 3CM', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0520', 'nama_produk' => 'Garputala Yamaha 3CM', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0521', 'nama_produk' => 'Garputala Yamaha 3CM', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0522', 'nama_produk' => 'Garputala Yamaha 3CM', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0523', 'nama_produk' => 'Garputala Yamaha 3CM', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0524', 'nama_produk' => 'Garputala Yamaha 3CM', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0525', 'nama_produk' => 'Garputala Yamaha 3CM', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0526', 'nama_produk' => 'NO SMOKING', 'variasi' => '-', 'hpp' => 9000],
            ['sku' => 'EMB0527', 'nama_produk' => 'BARBIE', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0528', 'nama_produk' => 'BARBIE', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0529', 'nama_produk' => 'BARBIE', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0530', 'nama_produk' => 'BARBIE', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0531', 'nama_produk' => 'BARBIE', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0532', 'nama_produk' => 'BARBIE', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0533', 'nama_produk' => 'BARBIE', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0534', 'nama_produk' => 'ALHAMDULILLAH FOR EVERYTHING', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0535', 'nama_produk' => 'ALHAMDULILLAH FOR EVERYTHING', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0536', 'nama_produk' => 'ALHAMDULILLAH FOR EVERYTHING', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0537', 'nama_produk' => 'ALHAMDULILLAH FOR EVERYTHING', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0538', 'nama_produk' => 'ALHAMDULILLAH FOR EVERYTHING', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0539', 'nama_produk' => 'ALHAMDULILLAH FOR EVERYTHING', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0540', 'nama_produk' => 'ALHAMDULILLAH FOR EVERYTHING', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0541', 'nama_produk' => 'GAK SENGAJA GANTENG', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0542', 'nama_produk' => 'GAK SENGAJA GANTENG', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0543', 'nama_produk' => 'GAK SENGAJA GANTENG', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0544', 'nama_produk' => 'GAK SENGAJA GANTENG', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0545', 'nama_produk' => 'GAK SENGAJA GANTENG', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0546', 'nama_produk' => 'GAK SENGAJA GANTENG', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0547', 'nama_produk' => 'GAK SENGAJA GANTENG', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0548', 'nama_produk' => 'KALANGAN PERINTIS', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0549', 'nama_produk' => 'KALANGAN PERINTIS', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0550', 'nama_produk' => 'KALANGAN PERINTIS', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0551', 'nama_produk' => 'KALANGAN PERINTIS', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0552', 'nama_produk' => 'KALANGAN PERINTIS', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0553', 'nama_produk' => 'KALANGAN PERINTIS', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0554', 'nama_produk' => 'KALANGAN PERINTIS', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0555', 'nama_produk' => 'BUKAN HASIL WARISAN', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0556', 'nama_produk' => 'BUKAN HASIL WARISAN', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0557', 'nama_produk' => 'BUKAN HASIL WARISAN', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0558', 'nama_produk' => 'BUKAN HASIL WARISAN', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0559', 'nama_produk' => 'BUKAN HASIL WARISAN', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0560', 'nama_produk' => 'BUKAN HASIL WARISAN', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0561', 'nama_produk' => 'BUKAN HASIL WARISAN', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0562', 'nama_produk' => 'NMAX JAPAN', 'variasi' => 'GOLD', 'hpp' => 16000],
            ['sku' => 'EMB0563', 'nama_produk' => 'NMAX JAPAN', 'variasi' => 'SILVER', 'hpp' => 16000],
            ['sku' => 'EMB0564', 'nama_produk' => 'NMAX JAPAN', 'variasi' => 'MERAH', 'hpp' => 16000],
            ['sku' => 'EMB0565', 'nama_produk' => 'NMAX JAPAN', 'variasi' => 'BIRU', 'hpp' => 16000],
            ['sku' => 'EMB0566', 'nama_produk' => 'NMAX JAPAN', 'variasi' => 'HITAM', 'hpp' => 16000],
            ['sku' => 'EMB0567', 'nama_produk' => 'NMAX JAPAN', 'variasi' => 'HIJAU', 'hpp' => 16000],
            ['sku' => 'EMB0568', 'nama_produk' => 'NMAX JAPAN', 'variasi' => 'PINK', 'hpp' => 16000],
            ['sku' => 'EMB0569', 'nama_produk' => 'STARLET', 'variasi' => '-', 'hpp' => 9000],
            ['sku' => 'EMB0570', 'nama_produk' => 'RED DEVIL', 'variasi' => '-', 'hpp' => 9000],
            ['sku' => 'EMB0571', 'nama_produk' => 'INTER MILAN', 'variasi' => '-', 'hpp' => 9000],
            ['sku' => 'EMB0572', 'nama_produk' => '4x4', 'variasi' => 'SILVER(4MILI)', 'hpp' => 9000],
            ['sku' => 'EMB0573', 'nama_produk' => 'JAPAN KANJI', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0574', 'nama_produk' => 'JAPAN KANJI', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0575', 'nama_produk' => 'JAPAN KANJI', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0576', 'nama_produk' => 'JAPAN KANJI', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0577', 'nama_produk' => 'JAPAN KANJI', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0578', 'nama_produk' => 'JAPAN KANJI', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0579', 'nama_produk' => 'JAPAN KANJI', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0580', 'nama_produk' => 'TIMBANG MLAKU V2', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0581', 'nama_produk' => 'TIMBANG MLAKU V2', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0582', 'nama_produk' => 'TIMBANG MLAKU V2', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0583', 'nama_produk' => 'TIMBANG MLAKU V2', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0584', 'nama_produk' => 'TIMBANG MLAKU V2', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0585', 'nama_produk' => 'TIMBANG MLAKU V2', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0586', 'nama_produk' => 'TIMBANG MLAKU V2', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0587', 'nama_produk' => 'BUKAN FASILITAS NEGARA', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0588', 'nama_produk' => 'BUKAN FASILITAS NEGARA', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0589', 'nama_produk' => 'BUKAN FASILITAS NEGARA', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0590', 'nama_produk' => 'BUKAN FASILITAS NEGARA', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0591', 'nama_produk' => 'BUKAN FASILITAS NEGARA', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0592', 'nama_produk' => 'BUKAN FASILITAS NEGARA', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0593', 'nama_produk' => 'BUKAN FASILITAS NEGARA', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0594', 'nama_produk' => 'TRASNFORMERS', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0595', 'nama_produk' => 'TRASNFORMERS', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0596', 'nama_produk' => 'TRASNFORMERS', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0597', 'nama_produk' => 'TRASNFORMERS', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0598', 'nama_produk' => 'TRASNFORMERS', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0599', 'nama_produk' => 'TRASNFORMERS', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0600', 'nama_produk' => 'TRASNFORMERS', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0601', 'nama_produk' => 'MAHJONG', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0602', 'nama_produk' => 'MAHJONG', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0603', 'nama_produk' => '70 DELUXE', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0604', 'nama_produk' => '70 DELUXE', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0605', 'nama_produk' => '70 DELUXE', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0606', 'nama_produk' => '70 DELUXE', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0607', 'nama_produk' => '70 DELUXE', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0608', 'nama_produk' => '70 DELUXE', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0609', 'nama_produk' => '70 DELUXE', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0610', 'nama_produk' => 'PIKACHU', 'variasi' => '-', 'hpp' => 9000],
            ['sku' => 'EMB0611', 'nama_produk' => 'KAMEN RIDER', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0612', 'nama_produk' => 'KAMEN RIDER', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0613', 'nama_produk' => 'KAMEN RIDER', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0614', 'nama_produk' => 'KAMEN RIDER', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0615', 'nama_produk' => 'KAMEN RIDER', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0616', 'nama_produk' => 'KAMEN RIDER', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0617', 'nama_produk' => 'KAMEN RIDER', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0618', 'nama_produk' => 'DINO T-REX', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0619', 'nama_produk' => 'DINO T-REX', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0620', 'nama_produk' => 'DINO T-REX', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0621', 'nama_produk' => 'DINO T-REX', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0622', 'nama_produk' => 'DINO T-REX', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0623', 'nama_produk' => 'DINO T-REX', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0624', 'nama_produk' => 'DINO T-REX', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0625', 'nama_produk' => 'FCK YOU', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0626', 'nama_produk' => 'FCK YOU', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0627', 'nama_produk' => 'FCK YOU', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0628', 'nama_produk' => 'FCK YOU', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0629', 'nama_produk' => 'FCK YOU', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0630', 'nama_produk' => 'FCK YOU', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0631', 'nama_produk' => 'FCK YOU', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0632', 'nama_produk' => 'CHELSEA FC', 'variasi' => '-', 'hpp' => 9000],
            ['sku' => 'EMB0633', 'nama_produk' => 'PUNISHER TENGKORAK', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0634', 'nama_produk' => 'PUNISHER TENGKORAK', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0635', 'nama_produk' => 'PUNISHER TENGKORAK', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0636', 'nama_produk' => 'PUNISHER TENGKORAK', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0637', 'nama_produk' => 'PUNISHER TENGKORAK', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0638', 'nama_produk' => 'PUNISHER TENGKORAK', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0639', 'nama_produk' => 'PUNISHER TENGKORAK', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0640', 'nama_produk' => 'REFLEKTOR SCOOPY', 'variasi' => 'Silver-Gold', 'hpp' => 9000],
            ['sku' => 'EMB0641', 'nama_produk' => 'REFLEKTOR SCOOPY', 'variasi' => 'Silver-Merah', 'hpp' => 9000],
            ['sku' => 'EMB0642', 'nama_produk' => 'REFLEKTOR SCOOPY', 'variasi' => 'Silver-Biru', 'hpp' => 9000],
            ['sku' => 'EMB0643', 'nama_produk' => 'REFLEKTOR SCOOPY', 'variasi' => 'Silver-Hijau', 'hpp' => 9000],
            ['sku' => 'EMB0644', 'nama_produk' => 'REFLEKTOR SCOOPY', 'variasi' => 'Silver-Pink', 'hpp' => 9000],
            ['sku' => 'EMB0645', 'nama_produk' => 'REFLEKTOR SCOOPY', 'variasi' => 'Gold-Silver', 'hpp' => 9000],
            ['sku' => 'EMB0646', 'nama_produk' => 'REFLEKTOR SCOOPY', 'variasi' => 'Gold-Merah', 'hpp' => 9000],
            ['sku' => 'EMB0647', 'nama_produk' => 'REFLEKTOR SCOOPY', 'variasi' => 'Gold-Biru', 'hpp' => 9000],
            ['sku' => 'EMB0648', 'nama_produk' => 'REFLEKTOR SCOOPY', 'variasi' => 'Gold-Hijau', 'hpp' => 9000],
            ['sku' => 'EMB0649', 'nama_produk' => 'REFLEKTOR SCOOPY', 'variasi' => 'Merah-Biru', 'hpp' => 9000],
            ['sku' => 'EMB0650', 'nama_produk' => 'REFLEKTOR SCOOPY', 'variasi' => 'Merah-Hijau', 'hpp' => 9000],
            ['sku' => 'EMB0651', 'nama_produk' => 'REFLEKTOR SCOOPY', 'variasi' => 'Merah-Gold', 'hpp' => 9000],
            ['sku' => 'EMB0652', 'nama_produk' => 'REFLEKTOR SCOOPY', 'variasi' => 'Merah-Silver', 'hpp' => 9000],
            ['sku' => 'EMB0653', 'nama_produk' => 'REFLEKTOR SCOOPY', 'variasi' => 'Biru-Gold', 'hpp' => 9000],
            ['sku' => 'EMB0654', 'nama_produk' => 'REFLEKTOR SCOOPY', 'variasi' => 'Biru-Pink', 'hpp' => 9000],
            ['sku' => 'EMB0655', 'nama_produk' => 'REFLEKTOR SCOOPY', 'variasi' => 'Biru-Silver', 'hpp' => 9000],
            ['sku' => 'EMB0656', 'nama_produk' => 'REFLEKTOR SCOOPY', 'variasi' => 'Biru-Merah', 'hpp' => 9000],
            ['sku' => 'EMB0657', 'nama_produk' => 'REFLEKTOR SCOOPY', 'variasi' => 'Pink-Merah', 'hpp' => 9000],
            ['sku' => 'EMB0658', 'nama_produk' => 'REFLEKTOR SCOOPY', 'variasi' => 'Pink-Silver', 'hpp' => 9000],
            ['sku' => 'EMB0659', 'nama_produk' => 'REFLEKTOR SCOOPY', 'variasi' => 'Pink-Hitam', 'hpp' => 9000],
            ['sku' => 'EMB0660', 'nama_produk' => 'REFLEKTOR SCOOPY', 'variasi' => 'Hijau-Gold', 'hpp' => 9000],
            ['sku' => 'EMB0661', 'nama_produk' => 'REFLEKTOR NMAX', 'variasi' => 'Silver-Gold', 'hpp' => 9000],
            ['sku' => 'EMB0662', 'nama_produk' => 'REFLEKTOR NMAX', 'variasi' => 'Silver-Merah', 'hpp' => 9000],
            ['sku' => 'EMB0663', 'nama_produk' => 'REFLEKTOR NMAX', 'variasi' => 'Silver-Biru', 'hpp' => 9000],
            ['sku' => 'EMB0664', 'nama_produk' => 'REFLEKTOR NMAX', 'variasi' => 'Silver-Hijau', 'hpp' => 9000],
            ['sku' => 'EMB0665', 'nama_produk' => 'REFLEKTOR NMAX', 'variasi' => 'Silver-Pink', 'hpp' => 9000],
            ['sku' => 'EMB0666', 'nama_produk' => 'REFLEKTOR NMAX', 'variasi' => 'Gold-Silver', 'hpp' => 9000],
            ['sku' => 'EMB0667', 'nama_produk' => 'REFLEKTOR NMAX', 'variasi' => 'Gold-Merah', 'hpp' => 9000],
            ['sku' => 'EMB0668', 'nama_produk' => 'REFLEKTOR NMAX', 'variasi' => 'Gold-Biru', 'hpp' => 9000],
            ['sku' => 'EMB0669', 'nama_produk' => 'REFLEKTOR NMAX', 'variasi' => 'Gold-Hijau', 'hpp' => 9000],
            ['sku' => 'EMB0670', 'nama_produk' => 'REFLEKTOR NMAX', 'variasi' => 'Merah-Biru', 'hpp' => 9000],
            ['sku' => 'EMB0671', 'nama_produk' => 'REFLEKTOR NMAX', 'variasi' => 'Merah-Hijau', 'hpp' => 9000],
            ['sku' => 'EMB0672', 'nama_produk' => 'REFLEKTOR NMAX', 'variasi' => 'Merah-Gold', 'hpp' => 9000],
            ['sku' => 'EMB0673', 'nama_produk' => 'REFLEKTOR NMAX', 'variasi' => 'Merah-Silver', 'hpp' => 9000],
            ['sku' => 'EMB0674', 'nama_produk' => 'REFLEKTOR NMAX', 'variasi' => 'Biru-Gold', 'hpp' => 9000],
            ['sku' => 'EMB0675', 'nama_produk' => 'REFLEKTOR NMAX', 'variasi' => 'Biru-Pink', 'hpp' => 9000],
            ['sku' => 'EMB0676', 'nama_produk' => 'REFLEKTOR NMAX', 'variasi' => 'Biru-Silver', 'hpp' => 9000],
            ['sku' => 'EMB0677', 'nama_produk' => 'REFLEKTOR NMAX', 'variasi' => 'Biru-Merah', 'hpp' => 9000],
            ['sku' => 'EMB0678', 'nama_produk' => 'REFLEKTOR NMAX', 'variasi' => 'Pink-Merah', 'hpp' => 9000],
            ['sku' => 'EMB0679', 'nama_produk' => 'REFLEKTOR NMAX', 'variasi' => 'Pink-Silver', 'hpp' => 9000],
            ['sku' => 'EMB0680', 'nama_produk' => 'REFLEKTOR NMAX', 'variasi' => 'Pink-Hitam', 'hpp' => 9000],
            ['sku' => 'EMB0681', 'nama_produk' => 'REFLEKTOR NMAX', 'variasi' => 'Hijau-Gold', 'hpp' => 9000],
            ['sku' => 'EMB0682', 'nama_produk' => 'Garputala Yamaha 4,5CM', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0683', 'nama_produk' => 'Garputala Yamaha 4,5CM', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0684', 'nama_produk' => 'Garputala Yamaha 4,5CM', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0685', 'nama_produk' => 'Garputala Yamaha 4,5CM', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0686', 'nama_produk' => 'Garputala Yamaha 4,5CM', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0687', 'nama_produk' => 'Garputala Yamaha 4,5CM', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0688', 'nama_produk' => 'Garputala Yamaha 4,5CM', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0689', 'nama_produk' => 'PRESTIGE HONDA', 'variasi' => 'HITAM GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0690', 'nama_produk' => 'PRESTIGE HONDA', 'variasi' => 'HTAM SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0691', 'nama_produk' => 'PRESTIGE HONDA', 'variasi' => 'HITAM MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0692', 'nama_produk' => 'PRESTIGE HONDA', 'variasi' => 'MERAH GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0693', 'nama_produk' => 'PRESTIGE HONDA', 'variasi' => 'MERAH SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0694', 'nama_produk' => 'REFLEKTOR VARIO', 'variasi' => 'Silver-Gold', 'hpp' => 9000],
            ['sku' => 'EMB0695', 'nama_produk' => 'REFLEKTOR VARIO', 'variasi' => 'Silver-Merah', 'hpp' => 9000],
            ['sku' => 'EMB0696', 'nama_produk' => 'REFLEKTOR VARIO', 'variasi' => 'Silver-Biru', 'hpp' => 9000],
            ['sku' => 'EMB0697', 'nama_produk' => 'REFLEKTOR VARIO', 'variasi' => 'Silver-Hijau', 'hpp' => 9000],
            ['sku' => 'EMB0698', 'nama_produk' => 'REFLEKTOR VARIO', 'variasi' => 'Silver-Pink', 'hpp' => 9000],
            ['sku' => 'EMB0699', 'nama_produk' => 'REFLEKTOR VARIO', 'variasi' => 'Gold-Silver', 'hpp' => 9000],
            ['sku' => 'EMB0700', 'nama_produk' => 'REFLEKTOR VARIO', 'variasi' => 'Gold-Merah', 'hpp' => 9000],
            ['sku' => 'EMB0701', 'nama_produk' => 'REFLEKTOR VARIO', 'variasi' => 'Gold-Biru', 'hpp' => 9000],
            ['sku' => 'EMB0702', 'nama_produk' => 'REFLEKTOR VARIO', 'variasi' => 'Gold-Hijau', 'hpp' => 9000],
            ['sku' => 'EMB0703', 'nama_produk' => 'REFLEKTOR VARIO', 'variasi' => 'Merah-Biru', 'hpp' => 9000],
            ['sku' => 'EMB0704', 'nama_produk' => 'REFLEKTOR VARIO', 'variasi' => 'Merah-Hijau', 'hpp' => 9000],
            ['sku' => 'EMB0705', 'nama_produk' => 'REFLEKTOR VARIO', 'variasi' => 'Merah-Gold', 'hpp' => 9000],
            ['sku' => 'EMB0706', 'nama_produk' => 'REFLEKTOR VARIO', 'variasi' => 'Merah-Silver', 'hpp' => 9000],
            ['sku' => 'EMB0707', 'nama_produk' => 'REFLEKTOR VARIO', 'variasi' => 'Biru-Gold', 'hpp' => 9000],
            ['sku' => 'EMB0708', 'nama_produk' => 'REFLEKTOR VARIO', 'variasi' => 'Biru-Pink', 'hpp' => 9000],
            ['sku' => 'EMB0709', 'nama_produk' => 'REFLEKTOR VARIO', 'variasi' => 'Biru-Silver', 'hpp' => 9000],
            ['sku' => 'EMB0710', 'nama_produk' => 'REFLEKTOR VARIO', 'variasi' => 'Biru-Merah', 'hpp' => 9000],
            ['sku' => 'EMB0711', 'nama_produk' => 'REFLEKTOR VARIO', 'variasi' => 'Pink-Merah', 'hpp' => 9000],
            ['sku' => 'EMB0712', 'nama_produk' => 'REFLEKTOR VARIO', 'variasi' => 'Pink-Silver', 'hpp' => 9000],
            ['sku' => 'EMB0713', 'nama_produk' => 'REFLEKTOR VARIO', 'variasi' => 'Pink-Hitam', 'hpp' => 9000],
            ['sku' => 'EMB0714', 'nama_produk' => 'REFLEKTOR VARIO', 'variasi' => 'Hijau-Gold', 'hpp' => 9000],
            ['sku' => 'EMB0715', 'nama_produk' => 'KABEH DULUR NEK SUGIH', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0716', 'nama_produk' => 'KABEH DULUR NEK SUGIH', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0717', 'nama_produk' => 'KABEH DULUR NEK SUGIH', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0718', 'nama_produk' => 'KABEH DULUR NEK SUGIH', 'variasi' => 'BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0719', 'nama_produk' => 'KABEH DULUR NEK SUGIH', 'variasi' => 'HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0720', 'nama_produk' => 'KABEH DULUR NEK SUGIH', 'variasi' => 'HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0721', 'nama_produk' => 'KABEH DULUR NEK SUGIH', 'variasi' => 'PINK', 'hpp' => 9000],
            ['sku' => 'EMB0722', 'nama_produk' => 'ELEK YO EBEN', 'variasi' => 'SILVER MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0723', 'nama_produk' => 'ELEK YO EBEN', 'variasi' => 'MERAH SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0724', 'nama_produk' => 'ELEK YO EBEN', 'variasi' => 'SILVER GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0725', 'nama_produk' => 'ELEK YO EBEN', 'variasi' => 'SILVER BIRU', 'hpp' => 9000],
            ['sku' => 'EMB0726', 'nama_produk' => 'ELEK YO EBEN', 'variasi' => 'SILVER HIJAU', 'hpp' => 9000],
            ['sku' => 'EMB0727', 'nama_produk' => 'ELEK YO EBEN', 'variasi' => 'SILVER HITAM', 'hpp' => 9000],
            ['sku' => 'EMB0728', 'nama_produk' => 'ELEK YO EBEN', 'variasi' => 'SILVER PINK', 'hpp' => 9000],
            ['sku' => 'EMB0729', 'nama_produk' => 'BATMAN', 'variasi' => 'GOLD', 'hpp' => 9000],
            ['sku' => 'EMB0730', 'nama_produk' => 'BATMAN', 'variasi' => 'SILVER', 'hpp' => 9000],
            ['sku' => 'EMB0731', 'nama_produk' => 'BATMAN', 'variasi' => 'MERAH', 'hpp' => 9000],
            ['sku' => 'EMB0732', 'nama_produk' => 'BATMAN', 'variasi' => 'BIRU', 'hpp' => 9000],
        ];

        DB::transaction(function () use ($data, $kategori) {
            $skuSeeder = collect($data)->pluck('sku');

            $duplicateSeeder = $skuSeeder
                ->duplicates()
                ->unique()
                ->values();

            if ($duplicateSeeder->isNotEmpty()) {
                throw new \Exception(
                    'SKU duplicate di data seeder: '.
                    $duplicateSeeder->implode(', ')
                );
            }

            foreach ($data as $item) {
                Produk::updateOrCreate(
                    [
                        'sku' => $item['sku'],
                    ],
                    [
                        'nama_produk' => $item['nama_produk'],
                        'variasi' => $item['variasi'],
                        'hpp' => $item['hpp'],
                        'kategori_id' => $kategori->id,
                    ]
                );
            }

        });
    }
}
