<?php

namespace Database\Seeders;

use App\Models\kategori;
use App\Models\Produk;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use RuntimeException;

class KaligrafiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        /*
         * Pastikan KategoriSeeder dijalankan terlebih dahulu
         * dan kategori "Kaligrafi" sudah tersedia.
         */
        $kategori = kategori::where('nama_kategori', 'KALIGRAFI')->first();

        if (! $kategori) {
            throw new RuntimeException(
                'Kategori Kaligrafi tidak ditemukan. Jalankan KategoriSeeder terlebih dahulu.'
            );
        }

        $data = [
            ['sku' => 'KLG001', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD KABAH', 'variasi' => '1PCS ALLAH', 'hpp' => 30000],
            ['sku' => 'KLG002', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD KABAH', 'variasi' => '1PCS MUHAMMAD', 'hpp' => 30000],
            ['sku' => 'KLG003', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD KABAH', 'variasi' => '1PCS KA\'BAH', 'hpp' => 30000],
            ['sku' => 'KLG004', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A05', 'variasi' => 'Gold,30 x 40 cm', 'hpp' => 114000],
            ['sku' => 'KLG005', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A05', 'variasi' => 'Gold,22 X 30 cm', 'hpp' => 62000],
            ['sku' => 'KLG006', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A05', 'variasi' => 'Gold,15 X 20 cm', 'hpp' => 31000],
            ['sku' => 'KLG007', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A05', 'variasi' => 'Silver,30 x 40 cm', 'hpp' => 114000],
            ['sku' => 'KLG008', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A05', 'variasi' => 'Silver,22 X 30 cm', 'hpp' => 62000],
            ['sku' => 'KLG009', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A05', 'variasi' => 'Silver,15 X 20 cm', 'hpp' => 31000],
            ['sku' => 'KLG010', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A05', 'variasi' => 'Hitam,30 x 40 cm', 'hpp' => 114000],
            ['sku' => 'KLG011', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A05', 'variasi' => 'Hitam,22 X 30 cm', 'hpp' => 62000],
            ['sku' => 'KLG012', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A05', 'variasi' => 'Hitam,15 X 20 cm', 'hpp' => 31000],
            ['sku' => 'KLG013', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A05', 'variasi' => 'Rose Gold,30 x 40 cm', 'hpp' => 114000],
            ['sku' => 'KLG014', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A05', 'variasi' => 'Rose Gold,22 X 30 cm', 'hpp' => 62000],
            ['sku' => 'KLG015', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A05', 'variasi' => 'Rose Gold,15 X 20 cm', 'hpp' => 31000],
            ['sku' => 'KLG016', 'nama_produk' => 'KALIGRAFI AYAT SERIBU DINAR A01', 'variasi' => 'Gold,60 x 20 cm', 'hpp' => 42000],
            ['sku' => 'KLG017', 'nama_produk' => 'KALIGRAFI AYAT SERIBU DINAR A01', 'variasi' => 'Gold,90 x 30 cm', 'hpp' => 91000],
            ['sku' => 'KLG018', 'nama_produk' => 'KALIGRAFI AYAT SERIBU DINAR A01', 'variasi' => 'Gold,120 x 40 cm', 'hpp' => 160000],
            ['sku' => 'KLG019', 'nama_produk' => 'KALIGRAFI AYAT SERIBU DINAR A01', 'variasi' => 'Silver,60 x 20 cm', 'hpp' => 42000],
            ['sku' => 'KLG020', 'nama_produk' => 'KALIGRAFI AYAT SERIBU DINAR A01', 'variasi' => 'Silver,90 x 30 cm', 'hpp' => 91000],
            ['sku' => 'KLG021', 'nama_produk' => 'KALIGRAFI AYAT SERIBU DINAR A01', 'variasi' => 'Silver,120 x 40 cm', 'hpp' => 160000],
            ['sku' => 'KLG022', 'nama_produk' => 'KALIGRAFI AYAT SERIBU DINAR A01', 'variasi' => 'Putih,60 x 20 cm', 'hpp' => 42000],
            ['sku' => 'KLG023', 'nama_produk' => 'KALIGRAFI AYAT SERIBU DINAR A01', 'variasi' => 'Putih,90 x 30 cm', 'hpp' => 91000],
            ['sku' => 'KLG024', 'nama_produk' => 'KALIGRAFI AYAT SERIBU DINAR A01', 'variasi' => 'Putih,120 x 40 cm', 'hpp' => 160000],
            ['sku' => 'KLG025', 'nama_produk' => 'KALIGRAFI AYAT SERIBU DINAR A01', 'variasi' => 'Hitam,60 x 20 cm', 'hpp' => 42000],
            ['sku' => 'KLG026', 'nama_produk' => 'KALIGRAFI AYAT SERIBU DINAR A01', 'variasi' => 'Hitam,90 x 30 cm', 'hpp' => 91000],
            ['sku' => 'KLG027', 'nama_produk' => 'KALIGRAFI AYAT SERIBU DINAR A01', 'variasi' => 'Hitam,120 x 40 cm', 'hpp' => 160000],
            ['sku' => 'KLG028', 'nama_produk' => 'KALIGRAFI AYAT SERIBU DINAR A01', 'variasi' => 'Rose Gold,60 x 20 cm', 'hpp' => 42000],
            ['sku' => 'KLG029', 'nama_produk' => 'KALIGRAFI AYAT SERIBU DINAR A01', 'variasi' => 'Rose Gold,90 x 30 cm', 'hpp' => 91000],
            ['sku' => 'KLG030', 'nama_produk' => 'KALIGRAFI AYAT SERIBU DINAR A01', 'variasi' => 'Rose Gold,120 x 40 cm', 'hpp' => 160000],
            ['sku' => 'KLG031', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A02', 'variasi' => 'Gold,40 x 40 cm', 'hpp' => 114000],
            ['sku' => 'KLG032', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A02', 'variasi' => 'Gold,30 x 30 cm', 'hpp' => 62000],
            ['sku' => 'KLG033', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A02', 'variasi' => 'Gold,20 x 20 cm', 'hpp' => 31000],
            ['sku' => 'KLG034', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A02', 'variasi' => 'Gold,10 x 10 cm', 'hpp' => 12000],
            ['sku' => 'KLG035', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A02', 'variasi' => 'Silver,40 x 40 cm', 'hpp' => 114000],
            ['sku' => 'KLG036', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A02', 'variasi' => 'Silver,30 x 30 cm', 'hpp' => 62000],
            ['sku' => 'KLG037', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A02', 'variasi' => 'Silver,20 x 20 cm', 'hpp' => 31000],
            ['sku' => 'KLG038', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A02', 'variasi' => 'Silver,10 x 10 cm', 'hpp' => 12000],
            ['sku' => 'KLG039', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A02', 'variasi' => 'Putih,40 x 40 cm', 'hpp' => 114000],
            ['sku' => 'KLG040', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A02', 'variasi' => 'Putih,30 x 30 cm', 'hpp' => 62000],
            ['sku' => 'KLG041', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A02', 'variasi' => 'Putih,20 x 20 cm', 'hpp' => 31000],
            ['sku' => 'KLG042', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A02', 'variasi' => 'Putih,10 x 10 cm', 'hpp' => 12000],
            ['sku' => 'KLG043', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A02', 'variasi' => 'Hitam,40 x 40 cm', 'hpp' => 114000],
            ['sku' => 'KLG044', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A02', 'variasi' => 'Hitam,30 x 30 cm', 'hpp' => 62000],
            ['sku' => 'KLG045', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A02', 'variasi' => 'Hitam,20 x 20 cm', 'hpp' => 31000],
            ['sku' => 'KLG046', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A02', 'variasi' => 'Hitam,10 x 10 cm', 'hpp' => 12000],
            ['sku' => 'KLG047', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A02', 'variasi' => 'Rose Gold,40 x 40 cm', 'hpp' => 114000],
            ['sku' => 'KLG048', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A02', 'variasi' => 'Rose Gold,30 x 30 cm', 'hpp' => 62000],
            ['sku' => 'KLG049', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A02', 'variasi' => 'Rose Gold,20 x 20 cm', 'hpp' => 31000],
            ['sku' => 'KLG050', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A02', 'variasi' => 'Rose Gold,10 x 10 cm', 'hpp' => 12000],
            ['sku' => 'KLG051', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL BULAT GOLD', 'variasi' => '1PCS AQSA GOLD,30 X 30 cm', 'hpp' => 33000],
            ['sku' => 'KLG052', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL BULAT GOLD', 'variasi' => '1PCS AQSA GOLD,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG053', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL BULAT GOLD', 'variasi' => '1PCS AQSA GOLD,15 X 15 cm', 'hpp' => 11000],
            ['sku' => 'KLG054', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL BULAT GOLD', 'variasi' => '1PCS NABAWI GOLD,30 X 30 cm', 'hpp' => 33000],
            ['sku' => 'KLG055', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL BULAT GOLD', 'variasi' => '1PCS NABAWI GOLD,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG056', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL BULAT GOLD', 'variasi' => '1PCS NABAWI GOLD,15 X 15 cm', 'hpp' => 11000],
            ['sku' => 'KLG057', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL BULAT GOLD', 'variasi' => '1PCS KABAH GOLD,30 X 30 cm', 'hpp' => 33000],
            ['sku' => 'KLG058', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL BULAT GOLD', 'variasi' => '1PCS KABAH GOLD,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG059', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL BULAT GOLD', 'variasi' => '1PCS KABAH GOLD,15 X 15 cm', 'hpp' => 11000],
            ['sku' => 'KLG060', 'nama_produk' => 'KALIGRAFI BISMILLAH A06', 'variasi' => 'Gold,50 x 17 cm', 'hpp' => 29000],
            ['sku' => 'KLG061', 'nama_produk' => 'KALIGRAFI BISMILLAH A06', 'variasi' => 'Gold,40 X 13,5 cm', 'hpp' => 20000],
            ['sku' => 'KLG062', 'nama_produk' => 'KALIGRAFI BISMILLAH A06', 'variasi' => 'Gold,30 X 10 cm', 'hpp' => 13000],
            ['sku' => 'KLG063', 'nama_produk' => 'KALIGRAFI BISMILLAH A06', 'variasi' => 'Silver,50 x 17 cm', 'hpp' => 29000],
            ['sku' => 'KLG064', 'nama_produk' => 'KALIGRAFI BISMILLAH A06', 'variasi' => 'Silver,40 X 13,5 cm', 'hpp' => 20000],
            ['sku' => 'KLG065', 'nama_produk' => 'KALIGRAFI BISMILLAH A06', 'variasi' => 'Silver,30 X 10 cm', 'hpp' => 13000],
            ['sku' => 'KLG066', 'nama_produk' => 'KALIGRAFI BISMILLAH A06', 'variasi' => 'Hitam,50 x 17 cm', 'hpp' => 29000],
            ['sku' => 'KLG067', 'nama_produk' => 'KALIGRAFI BISMILLAH A06', 'variasi' => 'Hitam,40 X 13,5 cm', 'hpp' => 20000],
            ['sku' => 'KLG068', 'nama_produk' => 'KALIGRAFI BISMILLAH A06', 'variasi' => 'Hitam,30 X 10 cm', 'hpp' => 13000],
            ['sku' => 'KLG069', 'nama_produk' => 'KALIGRAFI AYAT SERIBU DINAR GOLD PLYWOOD', 'variasi' => '60 Ã— 20 cm', 'hpp' => 20000],
            ['sku' => 'KLG070', 'nama_produk' => 'KALIGRAFI AYAT SERIBU DINAR GOLD PLYWOOD', 'variasi' => '90 Ã— 30 cm', 'hpp' => 40000],
            ['sku' => 'KLG071', 'nama_produk' => 'KALIGRAFI AYAT SERIBU DINAR GOLD PLYWOOD', 'variasi' => '120 Ã— 40 cm', 'hpp' => 80000],
            ['sku' => 'KLG072', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL KOTAK KOTAK GOLD', 'variasi' => '1PCS AQSA,40 x 27 cm', 'hpp' => 39000],
            ['sku' => 'KLG073', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL KOTAK KOTAK GOLD', 'variasi' => '1PCS AQSA,30 X 20 cm', 'hpp' => 21500],
            ['sku' => 'KLG074', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL KOTAK KOTAK GOLD', 'variasi' => '1PCS AQSA,15 X 10 cm', 'hpp' => 7000],
            ['sku' => 'KLG075', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL KOTAK KOTAK GOLD', 'variasi' => '1PCS NABAWI,40 x 27 cm', 'hpp' => 39000],
            ['sku' => 'KLG076', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL KOTAK KOTAK GOLD', 'variasi' => '1PCS NABAWI,30 X 20 cm', 'hpp' => 21500],
            ['sku' => 'KLG077', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL KOTAK KOTAK GOLD', 'variasi' => '1PCS NABAWI,15 X 10 cm', 'hpp' => 7000],
            ['sku' => 'KLG078', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL KOTAK KOTAK GOLD', 'variasi' => '1PCS KABAH,40 x 27 cm', 'hpp' => 39000],
            ['sku' => 'KLG079', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL KOTAK KOTAK GOLD', 'variasi' => '1PCS KABAH,30 X 20 cm', 'hpp' => 21500],
            ['sku' => 'KLG080', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL KOTAK KOTAK GOLD', 'variasi' => '1PCS KABAH,15 X 10 cm', 'hpp' => 7000],
            ['sku' => 'KLG081', 'nama_produk' => 'KALIGRAFI BISMILLAHIRRAHMANIRRAHIM', 'variasi' => 'Gold,40 x 15 cm', 'hpp' => 21500],
            ['sku' => 'KLG082', 'nama_produk' => 'KALIGRAFI BISMILLAHIRRAHMANIRRAHIM', 'variasi' => 'Gold,60 x 20 cm', 'hpp' => 42000],
            ['sku' => 'KLG083', 'nama_produk' => 'KALIGRAFI BISMILLAHIRRAHMANIRRAHIM', 'variasi' => 'Gold,80 x 25 cm', 'hpp' => 69000],
            ['sku' => 'KLG084', 'nama_produk' => 'KALIGRAFI BISMILLAHIRRAHMANIRRAHIM', 'variasi' => 'Hitam,40 x 15 cm', 'hpp' => 21500],
            ['sku' => 'KLG085', 'nama_produk' => 'KALIGRAFI BISMILLAHIRRAHMANIRRAHIM', 'variasi' => 'Hitam,60 x 20 cm', 'hpp' => 42000],
            ['sku' => 'KLG086', 'nama_produk' => 'KALIGRAFI BISMILLAHIRRAHMANIRRAHIM', 'variasi' => 'Hitam,80 x 25 cm', 'hpp' => 69000],
            ['sku' => 'KLG087', 'nama_produk' => 'KALIGRAFI BISMILLAHIRRAHMANIRRAHIM', 'variasi' => 'Silver,40 x 15 cm', 'hpp' => 21500],
            ['sku' => 'KLG088', 'nama_produk' => 'KALIGRAFI BISMILLAHIRRAHMANIRRAHIM', 'variasi' => 'Silver,60 x 20 cm', 'hpp' => 42000],
            ['sku' => 'KLG089', 'nama_produk' => 'KALIGRAFI BISMILLAHIRRAHMANIRRAHIM', 'variasi' => 'Silver,80 x 25 cm', 'hpp' => 69000],
            ['sku' => 'KLG090', 'nama_produk' => 'KALIGRAFI BISMILLAHIRRAHMANIRRAHIM', 'variasi' => 'Rose Gold,40 x 15 cm', 'hpp' => 21500],
            ['sku' => 'KLG091', 'nama_produk' => 'KALIGRAFI BISMILLAHIRRAHMANIRRAHIM', 'variasi' => 'Rose Gold,60 x 20 cm', 'hpp' => 42000],
            ['sku' => 'KLG092', 'nama_produk' => 'KALIGRAFI BISMILLAHIRRAHMANIRRAHIM', 'variasi' => 'Rose Gold,80 x 25 cm', 'hpp' => 69000],
            ['sku' => 'KLG093', 'nama_produk' => 'KALIGRAFI LAILAHAILLALLAH MUHAMMADARRASULULLAH A01', 'variasi' => 'Gold,60 x 20cm', 'hpp' => 42000],
            ['sku' => 'KLG094', 'nama_produk' => 'KALIGRAFI LAILAHAILLALLAH MUHAMMADARRASULULLAH A01', 'variasi' => 'Gold,100 x 40cm', 'hpp' => 137000],
            ['sku' => 'KLG095', 'nama_produk' => 'KALIGRAFI LAILAHAILLALLAH MUHAMMADARRASULULLAH A01', 'variasi' => 'Gold,120 x 40cm', 'hpp' => 160000],
            ['sku' => 'KLG096', 'nama_produk' => 'KALIGRAFI LAILAHAILLALLAH MUHAMMADARRASULULLAH A01', 'variasi' => 'Silver,60 x 20cm', 'hpp' => 42000],
            ['sku' => 'KLG097', 'nama_produk' => 'KALIGRAFI LAILAHAILLALLAH MUHAMMADARRASULULLAH A01', 'variasi' => 'Silver,100 x 40cm', 'hpp' => 137000],
            ['sku' => 'KLG098', 'nama_produk' => 'KALIGRAFI LAILAHAILLALLAH MUHAMMADARRASULULLAH A01', 'variasi' => 'Silver,120 x 40cm', 'hpp' => 160000],
            ['sku' => 'KLG099', 'nama_produk' => 'KALIGRAFI LAILAHAILLALLAH MUHAMMADARRASULULLAH A01', 'variasi' => 'Hitam,60 x 20cm', 'hpp' => 42000],
            ['sku' => 'KLG100', 'nama_produk' => 'KALIGRAFI LAILAHAILLALLAH MUHAMMADARRASULULLAH A01', 'variasi' => 'Hitam,100 x 40cm', 'hpp' => 137000],
            ['sku' => 'KLG101', 'nama_produk' => 'KALIGRAFI LAILAHAILLALLAH MUHAMMADARRASULULLAH A01', 'variasi' => 'Hitam,120 x 40cm', 'hpp' => 160000],
            ['sku' => 'KLG102', 'nama_produk' => 'KALIGRAFI LAILAHAILLALLAH MUHAMMADARRASULULLAH A01', 'variasi' => 'Rose Gold,60 x 20cm', 'hpp' => 42000],
            ['sku' => 'KLG103', 'nama_produk' => 'KALIGRAFI LAILAHAILLALLAH MUHAMMADARRASULULLAH A01', 'variasi' => 'Rose Gold,100 x 40cm', 'hpp' => 137000],
            ['sku' => 'KLG104', 'nama_produk' => 'KALIGRAFI LAILAHAILLALLAH MUHAMMADARRASULULLAH A01', 'variasi' => 'Rose Gold,120 x 40cm', 'hpp' => 160000],
            ['sku' => 'KLG105', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD TETESAN AIR A01', 'variasi' => 'Gold,27 x 40 cm', 'hpp' => 78000],
            ['sku' => 'KLG106', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD TETESAN AIR A01', 'variasi' => 'Gold,20 X 30 cm', 'hpp' => 43000],
            ['sku' => 'KLG107', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD TETESAN AIR A01', 'variasi' => 'Gold,10 X 15 cm', 'hpp' => 14000],
            ['sku' => 'KLG108', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD TETESAN AIR A01', 'variasi' => 'Silver,27 x 40 cm', 'hpp' => 78000],
            ['sku' => 'KLG109', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD TETESAN AIR A01', 'variasi' => 'Silver,20 X 30 cm', 'hpp' => 43000],
            ['sku' => 'KLG110', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD TETESAN AIR A01', 'variasi' => 'Silver,10 X 15 cm', 'hpp' => 14000],
            ['sku' => 'KLG111', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD TETESAN AIR A01', 'variasi' => 'Putih,27 x 40 cm', 'hpp' => 78000],
            ['sku' => 'KLG112', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD TETESAN AIR A01', 'variasi' => 'Putih,20 X 30 cm', 'hpp' => 43000],
            ['sku' => 'KLG113', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD TETESAN AIR A01', 'variasi' => 'Putih,10 X 15 cm', 'hpp' => 14000],
            ['sku' => 'KLG114', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD TETESAN AIR A01', 'variasi' => 'Hitam,27 x 40 cm', 'hpp' => 78000],
            ['sku' => 'KLG115', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD TETESAN AIR A01', 'variasi' => 'Hitam,20 X 30 cm', 'hpp' => 43000],
            ['sku' => 'KLG116', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD TETESAN AIR A01', 'variasi' => 'Hitam,10 X 15 cm', 'hpp' => 14000],
            ['sku' => 'KLG117', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD TETESAN AIR A01', 'variasi' => 'Rose Gold,27 x 40 cm', 'hpp' => 78000],
            ['sku' => 'KLG118', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD TETESAN AIR A01', 'variasi' => 'Rose Gold,20 X 30 cm', 'hpp' => 43000],
            ['sku' => 'KLG119', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD TETESAN AIR A01', 'variasi' => 'Rose Gold,10 X 15 cm', 'hpp' => 14000],
            ['sku' => 'KLG120', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL BULAT SILVER', 'variasi' => '1PCS AQSA SILVER,30 X 30 cm', 'hpp' => 93000],
            ['sku' => 'KLG121', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL BULAT SILVER', 'variasi' => '1PCS AQSA SILVER,20 X 20 cm', 'hpp' => 46500],
            ['sku' => 'KLG122', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL BULAT SILVER', 'variasi' => '1PCS AQSA SILVER,15 X 15 cm', 'hpp' => 33000],
            ['sku' => 'KLG123', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL BULAT SILVER', 'variasi' => '1PCS NABAWI SILVER,30 X 30 cm', 'hpp' => 93000],
            ['sku' => 'KLG124', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL BULAT SILVER', 'variasi' => '1PCS NABAWI SILVER,20 X 20 cm', 'hpp' => 46500],
            ['sku' => 'KLG125', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL BULAT SILVER', 'variasi' => '1PCS NABAWI SILVER,15 X 15 cm', 'hpp' => 33000],
            ['sku' => 'KLG126', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL BULAT SILVER', 'variasi' => '1PCS KABAH SILVER,30 X 30 cm', 'hpp' => 93000],
            ['sku' => 'KLG127', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL BULAT SILVER', 'variasi' => '1PCS KABAH SILVER,20 X 20 cm', 'hpp' => 46500],
            ['sku' => 'KLG128', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL BULAT SILVER', 'variasi' => '1PCS KABAH SILVER,15 X 15 cm', 'hpp' => 33000],
            ['sku' => 'KLG129', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A03', 'variasi' => 'Gold,27 x 40 cm', 'hpp' => 39000],
            ['sku' => 'KLG130', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A03', 'variasi' => 'Gold,20 X 30 cm', 'hpp' => 21500],
            ['sku' => 'KLG131', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A03', 'variasi' => 'Gold,10 X 15 cm', 'hpp' => 7000],
            ['sku' => 'KLG132', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A03', 'variasi' => 'Silver,27 x 40 cm', 'hpp' => 39000],
            ['sku' => 'KLG133', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A03', 'variasi' => 'Silver,20 X 30 cm', 'hpp' => 21500],
            ['sku' => 'KLG134', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A03', 'variasi' => 'Silver,10 X 15 cm', 'hpp' => 7000],
            ['sku' => 'KLG135', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A03', 'variasi' => 'Putih,27 x 40 cm', 'hpp' => 39000],
            ['sku' => 'KLG136', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A03', 'variasi' => 'Putih,20 X 30 cm', 'hpp' => 21500],
            ['sku' => 'KLG137', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A03', 'variasi' => 'Putih,10 X 15 cm', 'hpp' => 7000],
            ['sku' => 'KLG138', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A03', 'variasi' => 'Hitam,27 x 40 cm', 'hpp' => 39000],
            ['sku' => 'KLG139', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A03', 'variasi' => 'Hitam,20 X 30 cm', 'hpp' => 21500],
            ['sku' => 'KLG140', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A03', 'variasi' => 'Hitam,10 X 15 cm', 'hpp' => 7000],
            ['sku' => 'KLG141', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A03', 'variasi' => 'Rose Gold,27 x 40 cm', 'hpp' => 39000],
            ['sku' => 'KLG142', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A03', 'variasi' => 'Rose Gold,20 X 30 cm', 'hpp' => 21500],
            ['sku' => 'KLG143', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A03', 'variasi' => 'Rose Gold,10 X 15 cm', 'hpp' => 7000],
            ['sku' => 'KLG144', 'nama_produk' => 'KALIGRAFI LINGKARAN TAUHID A01', 'variasi' => 'Gold,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG145', 'nama_produk' => 'KALIGRAFI LINGKARAN TAUHID A01', 'variasi' => 'Gold,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG146', 'nama_produk' => 'KALIGRAFI LINGKARAN TAUHID A01', 'variasi' => 'Gold,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG147', 'nama_produk' => 'KALIGRAFI LINGKARAN TAUHID A01', 'variasi' => 'Silver,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG148', 'nama_produk' => 'KALIGRAFI LINGKARAN TAUHID A01', 'variasi' => 'Silver,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG149', 'nama_produk' => 'KALIGRAFI LINGKARAN TAUHID A01', 'variasi' => 'Silver,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG150', 'nama_produk' => 'KALIGRAFI LINGKARAN TAUHID A01', 'variasi' => 'Putih,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG151', 'nama_produk' => 'KALIGRAFI LINGKARAN TAUHID A01', 'variasi' => 'Putih,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG152', 'nama_produk' => 'KALIGRAFI LINGKARAN TAUHID A01', 'variasi' => 'Putih,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG153', 'nama_produk' => 'KALIGRAFI LINGKARAN TAUHID A01', 'variasi' => 'Hitam,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG154', 'nama_produk' => 'KALIGRAFI LINGKARAN TAUHID A01', 'variasi' => 'Hitam,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG155', 'nama_produk' => 'KALIGRAFI LINGKARAN TAUHID A01', 'variasi' => 'Hitam,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG156', 'nama_produk' => 'KALIGRAFI LINGKARAN TAUHID A01', 'variasi' => 'Rose Gold,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG157', 'nama_produk' => 'KALIGRAFI LINGKARAN TAUHID A01', 'variasi' => 'Rose Gold,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG158', 'nama_produk' => 'KALIGRAFI LINGKARAN TAUHID A01', 'variasi' => 'Rose Gold,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG159', 'nama_produk' => 'KALIGRAFI METAL BISMILLAH', 'variasi' => 'GOLD,40 cm x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG160', 'nama_produk' => 'KALIGRAFI METAL BISMILLAH', 'variasi' => 'GOLD,30 cm x 30 cm cm', 'hpp' => 31000],
            ['sku' => 'KLG161', 'nama_produk' => 'KALIGRAFI METAL BISMILLAH', 'variasi' => 'SILVER,40 cm x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG162', 'nama_produk' => 'KALIGRAFI METAL BISMILLAH', 'variasi' => 'SILVER,30 cm x 30 cm cm', 'hpp' => 31000],
            ['sku' => 'KLG163', 'nama_produk' => 'KALIGRAFI METAL BISMILLAH', 'variasi' => 'HITAM,40 cm x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG164', 'nama_produk' => 'KALIGRAFI METAL BISMILLAH', 'variasi' => 'HITAM,30 cm x 30 cm cm', 'hpp' => 31000],
            ['sku' => 'KLG165', 'nama_produk' => 'KALIGRAFI METAL BISMILLAH', 'variasi' => 'ROSE GOLD,40 cm x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG166', 'nama_produk' => 'KALIGRAFI METAL BISMILLAH', 'variasi' => 'ROSE GOLD,30 cm x 30 cm cm', 'hpp' => 31000],
            ['sku' => 'KLG167', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A04', 'variasi' => 'Gold,40 x 40 cm', 'hpp' => 114000],
            ['sku' => 'KLG168', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A04', 'variasi' => 'Gold,30 X 30 cm', 'hpp' => 62000],
            ['sku' => 'KLG169', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A04', 'variasi' => 'Gold,20 X 20 cm', 'hpp' => 31000],
            ['sku' => 'KLG170', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A04', 'variasi' => 'Silver,40 x 40 cm', 'hpp' => 114000],
            ['sku' => 'KLG171', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A04', 'variasi' => 'Silver,30 X 30 cm', 'hpp' => 62000],
            ['sku' => 'KLG172', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A04', 'variasi' => 'Silver,20 X 20 cm', 'hpp' => 31000],
            ['sku' => 'KLG173', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A04', 'variasi' => 'Hitam,40 x 40 cm', 'hpp' => 114000],
            ['sku' => 'KLG174', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A04', 'variasi' => 'Hitam,30 X 30 cm', 'hpp' => 62000],
            ['sku' => 'KLG175', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A04', 'variasi' => 'Hitam,20 X 20 cm', 'hpp' => 31000],
            ['sku' => 'KLG176', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A04', 'variasi' => 'Rose Gold,40 x 40 cm', 'hpp' => 114000],
            ['sku' => 'KLG177', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A04', 'variasi' => 'Rose Gold,30 X 30 cm', 'hpp' => 62000],
            ['sku' => 'KLG178', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD A04', 'variasi' => 'Rose Gold,20 X 20 cm', 'hpp' => 31000],
            ['sku' => 'KLG179', 'nama_produk' => 'KALIGRAFI BISMILLAH A01', 'variasi' => 'Gold,40 x 17 cm', 'hpp' => 24500],
            ['sku' => 'KLG180', 'nama_produk' => 'KALIGRAFI BISMILLAH A01', 'variasi' => 'Gold,30 X 13 cm', 'hpp' => 15500],
            ['sku' => 'KLG181', 'nama_produk' => 'KALIGRAFI BISMILLAH A01', 'variasi' => 'Gold,20 X 9 cm', 'hpp' => 8000],
            ['sku' => 'KLG182', 'nama_produk' => 'KALIGRAFI BISMILLAH A01', 'variasi' => 'Gold,10 X 5 cm', 'hpp' => 6000],
            ['sku' => 'KLG183', 'nama_produk' => 'KALIGRAFI BISMILLAH A01', 'variasi' => 'Silver,40 x 17 cm', 'hpp' => 24500],
            ['sku' => 'KLG184', 'nama_produk' => 'KALIGRAFI BISMILLAH A01', 'variasi' => 'Silver,30 X 13 cm', 'hpp' => 15500],
            ['sku' => 'KLG185', 'nama_produk' => 'KALIGRAFI BISMILLAH A01', 'variasi' => 'Silver,20 X 9 cm', 'hpp' => 8000],
            ['sku' => 'KLG186', 'nama_produk' => 'KALIGRAFI BISMILLAH A01', 'variasi' => 'Silver,10 X 5 cm', 'hpp' => 6000],
            ['sku' => 'KLG187', 'nama_produk' => 'KALIGRAFI BISMILLAH A01', 'variasi' => 'Putih,40 x 17 cm', 'hpp' => 24500],
            ['sku' => 'KLG188', 'nama_produk' => 'KALIGRAFI BISMILLAH A01', 'variasi' => 'Putih,30 X 13 cm', 'hpp' => 15500],
            ['sku' => 'KLG189', 'nama_produk' => 'KALIGRAFI BISMILLAH A01', 'variasi' => 'Putih,20 X 9 cm', 'hpp' => 8000],
            ['sku' => 'KLG190', 'nama_produk' => 'KALIGRAFI BISMILLAH A01', 'variasi' => 'Putih,10 X 5 cm', 'hpp' => 6000],
            ['sku' => 'KLG191', 'nama_produk' => 'KALIGRAFI BISMILLAH A01', 'variasi' => 'Hitam,40 x 17 cm', 'hpp' => 24500],
            ['sku' => 'KLG192', 'nama_produk' => 'KALIGRAFI BISMILLAH A01', 'variasi' => 'Hitam,30 X 13 cm', 'hpp' => 15500],
            ['sku' => 'KLG193', 'nama_produk' => 'KALIGRAFI BISMILLAH A01', 'variasi' => 'Hitam,20 X 9 cm', 'hpp' => 8000],
            ['sku' => 'KLG194', 'nama_produk' => 'KALIGRAFI BISMILLAH A01', 'variasi' => 'Hitam,10 X 5 cm', 'hpp' => 6000],
            ['sku' => 'KLG195', 'nama_produk' => 'KALIGRAFI BISMILLAH A01', 'variasi' => 'Rose Gold,40 x 17 cm', 'hpp' => 24500],
            ['sku' => 'KLG196', 'nama_produk' => 'KALIGRAFI BISMILLAH A01', 'variasi' => 'Rose Gold,30 X 13 cm', 'hpp' => 15500],
            ['sku' => 'KLG197', 'nama_produk' => 'KALIGRAFI BISMILLAH A01', 'variasi' => 'Rose Gold,20 X 9 cm', 'hpp' => 8000],
            ['sku' => 'KLG198', 'nama_produk' => 'KALIGRAFI BISMILLAH A01', 'variasi' => 'Rose Gold,10 X 5 cm', 'hpp' => 6000],
            ['sku' => 'KLG199', 'nama_produk' => 'KALIGRAFI ALLAHUMMA SHOLLI \'ALA MUHAMMAD WA AALI MUHAMMAD', 'variasi' => 'Gold,69 x 19 cm', 'hpp' => 48000],
            ['sku' => 'KLG200', 'nama_produk' => 'KALIGRAFI ALLAHUMMA SHOLLI \'ALA MUHAMMAD WA AALI MUHAMMAD', 'variasi' => 'Gold,98 x 28 cm', 'hpp' => 95000],
            ['sku' => 'KLG201', 'nama_produk' => 'KALIGRAFI ALLAHUMMA SHOLLI \'ALA MUHAMMAD WA AALI MUHAMMAD', 'variasi' => 'Hitam,69 x 19 cm', 'hpp' => 48000],
            ['sku' => 'KLG202', 'nama_produk' => 'KALIGRAFI ALLAHUMMA SHOLLI \'ALA MUHAMMAD WA AALI MUHAMMAD', 'variasi' => 'Hitam,98 x 28 cm', 'hpp' => 95000],
            ['sku' => 'KLG203', 'nama_produk' => 'KALIGRAFI ALLAHUMMA SHOLLI \'ALA MUHAMMAD WA AALI MUHAMMAD', 'variasi' => 'Silver,69 x 19 cm', 'hpp' => 48000],
            ['sku' => 'KLG204', 'nama_produk' => 'KALIGRAFI ALLAHUMMA SHOLLI \'ALA MUHAMMAD WA AALI MUHAMMAD', 'variasi' => 'Silver,98 x 28 cm', 'hpp' => 95000],
            ['sku' => 'KLG205', 'nama_produk' => 'KALIGRAFI ALLAHUMMA SHOLLI \'ALA MUHAMMAD WA AALI MUHAMMAD', 'variasi' => 'Rose Gold,69 x 19 cm', 'hpp' => 48000],
            ['sku' => 'KLG206', 'nama_produk' => 'KALIGRAFI ALLAHUMMA SHOLLI \'ALA MUHAMMAD WA AALI MUHAMMAD', 'variasi' => 'Rose Gold,98 x 28 cm', 'hpp' => 95000],
            ['sku' => 'KLG207', 'nama_produk' => 'KALIGRAFI LOVE A01', 'variasi' => 'Gold,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG208', 'nama_produk' => 'KALIGRAFI LOVE A01', 'variasi' => 'Gold,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG209', 'nama_produk' => 'KALIGRAFI LOVE A01', 'variasi' => 'Gold,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG210', 'nama_produk' => 'KALIGRAFI LOVE A01', 'variasi' => 'Gold,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG211', 'nama_produk' => 'KALIGRAFI LOVE A01', 'variasi' => 'Silver,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG212', 'nama_produk' => 'KALIGRAFI LOVE A01', 'variasi' => 'Silver,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG213', 'nama_produk' => 'KALIGRAFI LOVE A01', 'variasi' => 'Silver,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG214', 'nama_produk' => 'KALIGRAFI LOVE A01', 'variasi' => 'Silver,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG215', 'nama_produk' => 'KALIGRAFI LOVE A01', 'variasi' => 'Putih,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG216', 'nama_produk' => 'KALIGRAFI LOVE A01', 'variasi' => 'Putih,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG217', 'nama_produk' => 'KALIGRAFI LOVE A01', 'variasi' => 'Putih,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG218', 'nama_produk' => 'KALIGRAFI LOVE A01', 'variasi' => 'Putih,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG219', 'nama_produk' => 'KALIGRAFI LOVE A01', 'variasi' => 'Hitam,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG220', 'nama_produk' => 'KALIGRAFI LOVE A01', 'variasi' => 'Hitam,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG221', 'nama_produk' => 'KALIGRAFI LOVE A01', 'variasi' => 'Hitam,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG222', 'nama_produk' => 'KALIGRAFI LOVE A01', 'variasi' => 'Hitam,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG223', 'nama_produk' => 'KALIGRAFI LOVE A01', 'variasi' => 'Rose Gold,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG224', 'nama_produk' => 'KALIGRAFI LOVE A01', 'variasi' => 'Rose Gold,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG225', 'nama_produk' => 'KALIGRAFI LOVE A01', 'variasi' => 'Rose Gold,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG226', 'nama_produk' => 'KALIGRAFI LOVE A01', 'variasi' => 'Rose Gold,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG227', 'nama_produk' => 'KALIGRAFI BISMILLAH MODEL BULAT A04', 'variasi' => 'Gold,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG228', 'nama_produk' => 'KALIGRAFI BISMILLAH MODEL BULAT A04', 'variasi' => 'Gold,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG229', 'nama_produk' => 'KALIGRAFI BISMILLAH MODEL BULAT A04', 'variasi' => 'Gold,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG230', 'nama_produk' => 'KALIGRAFI BISMILLAH MODEL BULAT A04', 'variasi' => 'Gold,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG231', 'nama_produk' => 'KALIGRAFI BISMILLAH MODEL BULAT A04', 'variasi' => 'Silver,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG232', 'nama_produk' => 'KALIGRAFI BISMILLAH MODEL BULAT A04', 'variasi' => 'Silver,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG233', 'nama_produk' => 'KALIGRAFI BISMILLAH MODEL BULAT A04', 'variasi' => 'Silver,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG234', 'nama_produk' => 'KALIGRAFI BISMILLAH MODEL BULAT A04', 'variasi' => 'Silver,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG235', 'nama_produk' => 'KALIGRAFI BISMILLAH MODEL BULAT A04', 'variasi' => 'Putih,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG236', 'nama_produk' => 'KALIGRAFI BISMILLAH MODEL BULAT A04', 'variasi' => 'Putih,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG237', 'nama_produk' => 'KALIGRAFI BISMILLAH MODEL BULAT A04', 'variasi' => 'Putih,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG238', 'nama_produk' => 'KALIGRAFI BISMILLAH MODEL BULAT A04', 'variasi' => 'Putih,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG239', 'nama_produk' => 'KALIGRAFI BISMILLAH MODEL BULAT A04', 'variasi' => 'Hitam,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG240', 'nama_produk' => 'KALIGRAFI BISMILLAH MODEL BULAT A04', 'variasi' => 'Hitam,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG241', 'nama_produk' => 'KALIGRAFI BISMILLAH MODEL BULAT A04', 'variasi' => 'Hitam,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG242', 'nama_produk' => 'KALIGRAFI BISMILLAH MODEL BULAT A04', 'variasi' => 'Hitam,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG243', 'nama_produk' => 'KALIGRAFI BISMILLAH MODEL BULAT A04', 'variasi' => 'Rose Gold,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG244', 'nama_produk' => 'KALIGRAFI BISMILLAH MODEL BULAT A04', 'variasi' => 'Rose Gold,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG245', 'nama_produk' => 'KALIGRAFI BISMILLAH MODEL BULAT A04', 'variasi' => 'Rose Gold,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG246', 'nama_produk' => 'KALIGRAFI BISMILLAH MODEL BULAT A04', 'variasi' => 'Rose Gold,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG247', 'nama_produk' => 'KALIGRAFI RAMADAN KAREEM', 'variasi' => 'Gold,32 x 12 cm', 'hpp' => 13000],
            ['sku' => 'KLG248', 'nama_produk' => 'KALIGRAFI RAMADAN KAREEM', 'variasi' => 'Hitam,32 x 12 cm', 'hpp' => 13000],
            ['sku' => 'KLG249', 'nama_produk' => 'KALIGRAFI RAMADAN KAREEM', 'variasi' => 'Silver,32 x 12 cm', 'hpp' => 13000],
            ['sku' => 'KLG250', 'nama_produk' => 'KALIGRAFI RAMADAN KAREEM', 'variasi' => 'Rose Gold,32 x 12 cm', 'hpp' => 13000],
            ['sku' => 'KLG251', 'nama_produk' => 'KALIGRAFI ALLAH BULAN SABIT A01', 'variasi' => 'Gold,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG252', 'nama_produk' => 'KALIGRAFI ALLAH BULAN SABIT A01', 'variasi' => 'Gold,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG253', 'nama_produk' => 'KALIGRAFI ALLAH BULAN SABIT A01', 'variasi' => 'Gold,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG254', 'nama_produk' => 'KALIGRAFI ALLAH BULAN SABIT A01', 'variasi' => 'Gold,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG255', 'nama_produk' => 'KALIGRAFI ALLAH BULAN SABIT A01', 'variasi' => 'Silver,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG256', 'nama_produk' => 'KALIGRAFI ALLAH BULAN SABIT A01', 'variasi' => 'Silver,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG257', 'nama_produk' => 'KALIGRAFI ALLAH BULAN SABIT A01', 'variasi' => 'Silver,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG258', 'nama_produk' => 'KALIGRAFI ALLAH BULAN SABIT A01', 'variasi' => 'Silver,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG259', 'nama_produk' => 'KALIGRAFI ALLAH BULAN SABIT A01', 'variasi' => 'Putih,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG260', 'nama_produk' => 'KALIGRAFI ALLAH BULAN SABIT A01', 'variasi' => 'Putih,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG261', 'nama_produk' => 'KALIGRAFI ALLAH BULAN SABIT A01', 'variasi' => 'Putih,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG262', 'nama_produk' => 'KALIGRAFI ALLAH BULAN SABIT A01', 'variasi' => 'Putih,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG263', 'nama_produk' => 'KALIGRAFI ALLAH BULAN SABIT A01', 'variasi' => 'Hitam,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG264', 'nama_produk' => 'KALIGRAFI ALLAH BULAN SABIT A01', 'variasi' => 'Hitam,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG265', 'nama_produk' => 'KALIGRAFI ALLAH BULAN SABIT A01', 'variasi' => 'Hitam,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG266', 'nama_produk' => 'KALIGRAFI ALLAH BULAN SABIT A01', 'variasi' => 'Hitam,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG267', 'nama_produk' => 'KALIGRAFI ALLAH BULAN SABIT A01', 'variasi' => 'Rose Gold,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG268', 'nama_produk' => 'KALIGRAFI ALLAH BULAN SABIT A01', 'variasi' => 'Rose Gold,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG269', 'nama_produk' => 'KALIGRAFI ALLAH BULAN SABIT A01', 'variasi' => 'Rose Gold,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG270', 'nama_produk' => 'KALIGRAFI ALLAH BULAN SABIT A01', 'variasi' => 'Rose Gold,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG271', 'nama_produk' => 'KALIGRAFI ALLAH DESAIN LOVE A01', 'variasi' => 'Gold,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG272', 'nama_produk' => 'KALIGRAFI ALLAH DESAIN LOVE A01', 'variasi' => 'Gold,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG273', 'nama_produk' => 'KALIGRAFI ALLAH DESAIN LOVE A01', 'variasi' => 'Gold,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG274', 'nama_produk' => 'KALIGRAFI ALLAH DESAIN LOVE A01', 'variasi' => 'Gold,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG275', 'nama_produk' => 'KALIGRAFI ALLAH DESAIN LOVE A01', 'variasi' => 'Silver,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG276', 'nama_produk' => 'KALIGRAFI ALLAH DESAIN LOVE A01', 'variasi' => 'Silver,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG277', 'nama_produk' => 'KALIGRAFI ALLAH DESAIN LOVE A01', 'variasi' => 'Silver,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG278', 'nama_produk' => 'KALIGRAFI ALLAH DESAIN LOVE A01', 'variasi' => 'Silver,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG279', 'nama_produk' => 'KALIGRAFI ALLAH DESAIN LOVE A01', 'variasi' => 'Putih,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG280', 'nama_produk' => 'KALIGRAFI ALLAH DESAIN LOVE A01', 'variasi' => 'Putih,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG281', 'nama_produk' => 'KALIGRAFI ALLAH DESAIN LOVE A01', 'variasi' => 'Putih,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG282', 'nama_produk' => 'KALIGRAFI ALLAH DESAIN LOVE A01', 'variasi' => 'Putih,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG283', 'nama_produk' => 'KALIGRAFI ALLAH DESAIN LOVE A01', 'variasi' => 'Hitam,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG284', 'nama_produk' => 'KALIGRAFI ALLAH DESAIN LOVE A01', 'variasi' => 'Hitam,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG285', 'nama_produk' => 'KALIGRAFI ALLAH DESAIN LOVE A01', 'variasi' => 'Hitam,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG286', 'nama_produk' => 'KALIGRAFI ALLAH DESAIN LOVE A01', 'variasi' => 'Hitam,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG287', 'nama_produk' => 'KALIGRAFI ALLAH DESAIN LOVE A01', 'variasi' => 'Rose Gold,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG288', 'nama_produk' => 'KALIGRAFI ALLAH DESAIN LOVE A01', 'variasi' => 'Rose Gold,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG289', 'nama_produk' => 'KALIGRAFI ALLAH DESAIN LOVE A01', 'variasi' => 'Rose Gold,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG290', 'nama_produk' => 'KALIGRAFI ALLAH DESAIN LOVE A01', 'variasi' => 'Rose Gold,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG291', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD LINGKARAN TAUHID GOLD PLYWOOD', 'variasi' => '20Cm 1SET', 'hpp' => 22500],
            ['sku' => 'KLG292', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD LINGKARAN TAUHID GOLD PLYWOOD', 'variasi' => '30Cm 1SET', 'hpp' => 45000],
            ['sku' => 'KLG293', 'nama_produk' => 'KALIGRAFI ALLAH MUHAMMAD LINGKARAN TAUHID GOLD PLYWOOD', 'variasi' => '40Cm 1SET', 'hpp' => 80000],
            ['sku' => 'KLG294', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR SUBHAN ALLAH ALHAMDULILLAH 1SET', 'variasi' => '1SET Hitam Gold,27 x 40 cm', 'hpp' => 126000],
            ['sku' => 'KLG295', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR SUBHAN ALLAH ALHAMDULILLAH 1SET', 'variasi' => '1SET Hitam Gold,20 X 30 cm', 'hpp' => 70000],
            ['sku' => 'KLG296', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR SUBHAN ALLAH ALHAMDULILLAH 1SET', 'variasi' => '1SET Hitam Gold,10 X 15 cm', 'hpp' => 20000],
            ['sku' => 'KLG297', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR SUBHAN ALLAH ALHAMDULILLAH 1SET', 'variasi' => '1SET Hitam Silver,27 x 40 cm', 'hpp' => 126000],
            ['sku' => 'KLG298', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR SUBHAN ALLAH ALHAMDULILLAH 1SET', 'variasi' => '1SET Hitam Silver,20 X 30 cm', 'hpp' => 70000],
            ['sku' => 'KLG299', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR SUBHAN ALLAH ALHAMDULILLAH 1SET', 'variasi' => '1SET Hitam Silver,10 X 15 cm', 'hpp' => 20000],
            ['sku' => 'KLG300', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR SUBHAN ALLAH ALHAMDULILLAH 1SET', 'variasi' => '1SET Hitam Putih,27 x 40 cm', 'hpp' => 126000],
            ['sku' => 'KLG301', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR SUBHAN ALLAH ALHAMDULILLAH 1SET', 'variasi' => '1SET Hitam Putih,20 X 30 cm', 'hpp' => 70000],
            ['sku' => 'KLG302', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR SUBHAN ALLAH ALHAMDULILLAH 1SET', 'variasi' => '1SET Hitam Putih,10 X 15 cm', 'hpp' => 20000],
            ['sku' => 'KLG303', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR SUBHAN ALLAH ALHAMDULILLAH 1SET', 'variasi' => '1SET Putih Hitam,27 x 40 cm', 'hpp' => 126000],
            ['sku' => 'KLG304', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR SUBHAN ALLAH ALHAMDULILLAH 1SET', 'variasi' => '1SET Putih Hitam,20 X 30 cm', 'hpp' => 70000],
            ['sku' => 'KLG305', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR SUBHAN ALLAH ALHAMDULILLAH 1SET', 'variasi' => '1SET Putih Hitam,10 X 15 cm', 'hpp' => 20000],
            ['sku' => 'KLG306', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH A01', 'variasi' => 'Silver,40 x 20 cm', 'hpp' => 27500],
            ['sku' => 'KLG307', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH A01', 'variasi' => 'Silver,30 X 15 cm', 'hpp' => 17000],
            ['sku' => 'KLG308', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH A01', 'variasi' => 'Silver,15 X 10 cm', 'hpp' => 7000],
            ['sku' => 'KLG309', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH A01', 'variasi' => 'Putih,40 x 20 cm', 'hpp' => 27500],
            ['sku' => 'KLG310', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH A01', 'variasi' => 'Putih,30 X 15 cm', 'hpp' => 17000],
            ['sku' => 'KLG311', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH A01', 'variasi' => 'Putih,15 X 10 cm', 'hpp' => 7000],
            ['sku' => 'KLG312', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH A01', 'variasi' => 'Hitam,40 x 20 cm', 'hpp' => 27500],
            ['sku' => 'KLG313', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH A01', 'variasi' => 'Hitam,30 X 15 cm', 'hpp' => 17000],
            ['sku' => 'KLG314', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH A01', 'variasi' => 'Hitam,15 X 10 cm', 'hpp' => 7000],
            ['sku' => 'KLG315', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH A01', 'variasi' => 'Gold,40 x 20 cm', 'hpp' => 27500],
            ['sku' => 'KLG316', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH A01', 'variasi' => 'Gold,30 X 15 cm', 'hpp' => 17000],
            ['sku' => 'KLG317', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH A01', 'variasi' => 'Gold,15 X 10 cm', 'hpp' => 7000],
            ['sku' => 'KLG318', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH A01', 'variasi' => 'Rose Gold,40 x 20 cm', 'hpp' => 27500],
            ['sku' => 'KLG319', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH A01', 'variasi' => 'Rose Gold,30 X 15 cm', 'hpp' => 17000],
            ['sku' => 'KLG320', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH A01', 'variasi' => 'Rose Gold,15 X 10 cm', 'hpp' => 7000],
            ['sku' => 'KLG321', 'nama_produk' => 'KALIGRAFI BISMILLAH A02', 'variasi' => 'Gold,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG322', 'nama_produk' => 'KALIGRAFI BISMILLAH A02', 'variasi' => 'Gold,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG323', 'nama_produk' => 'KALIGRAFI BISMILLAH A02', 'variasi' => 'Gold,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG324', 'nama_produk' => 'KALIGRAFI BISMILLAH A02', 'variasi' => 'Gold,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG325', 'nama_produk' => 'KALIGRAFI BISMILLAH A02', 'variasi' => 'Silver,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG326', 'nama_produk' => 'KALIGRAFI BISMILLAH A02', 'variasi' => 'Silver,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG327', 'nama_produk' => 'KALIGRAFI BISMILLAH A02', 'variasi' => 'Silver,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG328', 'nama_produk' => 'KALIGRAFI BISMILLAH A02', 'variasi' => 'Silver,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG329', 'nama_produk' => 'KALIGRAFI BISMILLAH A02', 'variasi' => 'Putih,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG330', 'nama_produk' => 'KALIGRAFI BISMILLAH A02', 'variasi' => 'Putih,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG331', 'nama_produk' => 'KALIGRAFI BISMILLAH A02', 'variasi' => 'Putih,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG332', 'nama_produk' => 'KALIGRAFI BISMILLAH A02', 'variasi' => 'Putih,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG333', 'nama_produk' => 'KALIGRAFI BISMILLAH A02', 'variasi' => 'Hitam,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG334', 'nama_produk' => 'KALIGRAFI BISMILLAH A02', 'variasi' => 'Hitam,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG335', 'nama_produk' => 'KALIGRAFI BISMILLAH A02', 'variasi' => 'Hitam,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG336', 'nama_produk' => 'KALIGRAFI BISMILLAH A02', 'variasi' => 'Hitam,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG337', 'nama_produk' => 'KALIGRAFI BISMILLAH A02', 'variasi' => 'Rose Gold,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG338', 'nama_produk' => 'KALIGRAFI BISMILLAH A02', 'variasi' => 'Rose Gold,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG339', 'nama_produk' => 'KALIGRAFI BISMILLAH A02', 'variasi' => 'Rose Gold,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG340', 'nama_produk' => 'KALIGRAFI BISMILLAH A02', 'variasi' => 'Rose Gold,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG341', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR A01', 'variasi' => 'Gold,40 x 27 cm', 'hpp' => 39000],
            ['sku' => 'KLG342', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR A01', 'variasi' => 'Gold,30 X 20 cm', 'hpp' => 21500],
            ['sku' => 'KLG343', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR A01', 'variasi' => 'Gold,20 X 13 cm', 'hpp' => 13000],
            ['sku' => 'KLG344', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR A01', 'variasi' => 'Gold,15 X 10 cm', 'hpp' => 7000],
            ['sku' => 'KLG345', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR A01', 'variasi' => 'Silver,40 x 27 cm', 'hpp' => 39000],
            ['sku' => 'KLG346', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR A01', 'variasi' => 'Silver,30 X 20 cm', 'hpp' => 21500],
            ['sku' => 'KLG347', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR A01', 'variasi' => 'Silver,20 X 13 cm', 'hpp' => 13000],
            ['sku' => 'KLG348', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR A01', 'variasi' => 'Silver,15 X 10 cm', 'hpp' => 7000],
            ['sku' => 'KLG349', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR A01', 'variasi' => 'Putih,40 x 27 cm', 'hpp' => 39000],
            ['sku' => 'KLG350', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR A01', 'variasi' => 'Putih,30 X 20 cm', 'hpp' => 21500],
            ['sku' => 'KLG351', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR A01', 'variasi' => 'Putih,20 X 13 cm', 'hpp' => 13000],
            ['sku' => 'KLG352', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR A01', 'variasi' => 'Putih,15 X 10 cm', 'hpp' => 7000],
            ['sku' => 'KLG353', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR A01', 'variasi' => 'Hitam,40 x 27 cm', 'hpp' => 39000],
            ['sku' => 'KLG354', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR A01', 'variasi' => 'Hitam,30 X 20 cm', 'hpp' => 21500],
            ['sku' => 'KLG355', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR A01', 'variasi' => 'Hitam,20 X 13 cm', 'hpp' => 13000],
            ['sku' => 'KLG356', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR A01', 'variasi' => 'Hitam,15 X 10 cm', 'hpp' => 7000],
            ['sku' => 'KLG357', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR A01', 'variasi' => 'Rose Gold,40 x 27 cm', 'hpp' => 39000],
            ['sku' => 'KLG358', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR A01', 'variasi' => 'Rose Gold,30 X 20 cm', 'hpp' => 21500],
            ['sku' => 'KLG359', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR A01', 'variasi' => 'Rose Gold,20 X 13 cm', 'hpp' => 13000],
            ['sku' => 'KLG360', 'nama_produk' => 'KALIGRAFI ALLAHU AKBAR A01', 'variasi' => 'Rose Gold,15 X 10 cm', 'hpp' => 7000],
            ['sku' => 'KLG361', 'nama_produk' => 'KALIGRAFI AHLAN WA SAHLAN 30CM', 'variasi' => 'GOLD', 'hpp' => 13000],
            ['sku' => 'KLG362', 'nama_produk' => 'KALIGRAFI AHLAN WA SAHLAN 30CM', 'variasi' => 'SILVER', 'hpp' => 13000],
            ['sku' => 'KLG363', 'nama_produk' => 'KALIGRAFI AHLAN WA SAHLAN 30CM', 'variasi' => 'HITAM', 'hpp' => 13000],
            ['sku' => 'KLG364', 'nama_produk' => 'KALIGRAFI AHLAN WA SAHLAN 30CM', 'variasi' => 'ROSE GOLD', 'hpp' => 13000],
            ['sku' => 'KLG365', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL KOTAK SILVER', 'variasi' => '1PCS AQSA SILVER,40 x 27 cm', 'hpp' => 39000],
            ['sku' => 'KLG366', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL KOTAK SILVER', 'variasi' => '1PCS AQSA SILVER,30 X 20 cm', 'hpp' => 21500],
            ['sku' => 'KLG367', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL KOTAK SILVER', 'variasi' => '1PCS AQSA SILVER,15 X 10 cm', 'hpp' => 7000],
            ['sku' => 'KLG368', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL KOTAK SILVER', 'variasi' => '1PCS NABAWI SILVER,40 x 27 cm', 'hpp' => 39000],
            ['sku' => 'KLG369', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL KOTAK SILVER', 'variasi' => '1PCS NABAWI SILVER,30 X 20 cm', 'hpp' => 21500],
            ['sku' => 'KLG370', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL KOTAK SILVER', 'variasi' => '1PCS NABAWI SILVER,15 X 10 cm', 'hpp' => 7000],
            ['sku' => 'KLG371', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL KOTAK SILVER', 'variasi' => '1PCS KABAH SILVER,40 x 27 cm', 'hpp' => 39000],
            ['sku' => 'KLG372', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL KOTAK SILVER', 'variasi' => '1PCS KABAH SILVER,30 X 20 cm', 'hpp' => 21500],
            ['sku' => 'KLG373', 'nama_produk' => 'KALIGRAFI KABAH AQSA NABAWI MODEL KOTAK SILVER', 'variasi' => '1PCS KABAH SILVER,15 X 10 cm', 'hpp' => 7000],
            ['sku' => 'KLG374', 'nama_produk' => 'KALIGRAFI MUHAMMADROSUL A01', 'variasi' => 'Gold,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG375', 'nama_produk' => 'KALIGRAFI MUHAMMADROSUL A01', 'variasi' => 'Gold,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG376', 'nama_produk' => 'KALIGRAFI MUHAMMADROSUL A01', 'variasi' => 'Gold,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG377', 'nama_produk' => 'KALIGRAFI MUHAMMADROSUL A01', 'variasi' => 'Gold,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG378', 'nama_produk' => 'KALIGRAFI MUHAMMADROSUL A01', 'variasi' => 'Silver,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG379', 'nama_produk' => 'KALIGRAFI MUHAMMADROSUL A01', 'variasi' => 'Silver,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG380', 'nama_produk' => 'KALIGRAFI MUHAMMADROSUL A01', 'variasi' => 'Silver,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG381', 'nama_produk' => 'KALIGRAFI MUHAMMADROSUL A01', 'variasi' => 'Silver,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG382', 'nama_produk' => 'KALIGRAFI MUHAMMADROSUL A01', 'variasi' => 'Putih,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG383', 'nama_produk' => 'KALIGRAFI MUHAMMADROSUL A01', 'variasi' => 'Putih,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG384', 'nama_produk' => 'KALIGRAFI MUHAMMADROSUL A01', 'variasi' => 'Putih,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG385', 'nama_produk' => 'KALIGRAFI MUHAMMADROSUL A01', 'variasi' => 'Putih,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG386', 'nama_produk' => 'KALIGRAFI MUHAMMADROSUL A01', 'variasi' => 'Hitam,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG387', 'nama_produk' => 'KALIGRAFI MUHAMMADROSUL A01', 'variasi' => 'Hitam,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG388', 'nama_produk' => 'KALIGRAFI MUHAMMADROSUL A01', 'variasi' => 'Hitam,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG389', 'nama_produk' => 'KALIGRAFI MUHAMMADROSUL A01', 'variasi' => 'Hitam,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG390', 'nama_produk' => 'KALIGRAFI MUHAMMADROSUL A01', 'variasi' => 'Rose Gold,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG391', 'nama_produk' => 'KALIGRAFI MUHAMMADROSUL A01', 'variasi' => 'Rose Gold,30 X 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG392', 'nama_produk' => 'KALIGRAFI MUHAMMADROSUL A01', 'variasi' => 'Rose Gold,20 X 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG393', 'nama_produk' => 'KALIGRAFI MUHAMMADROSUL A01', 'variasi' => 'Rose Gold,10 X 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG394', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH DESAIN BULAN A02', 'variasi' => 'Gold,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG395', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH DESAIN BULAN A02', 'variasi' => 'Gold,30 x 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG396', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH DESAIN BULAN A02', 'variasi' => 'Gold,20 x 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG397', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH DESAIN BULAN A02', 'variasi' => 'Gold,10 x 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG398', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH DESAIN BULAN A02', 'variasi' => 'Silver,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG399', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH DESAIN BULAN A02', 'variasi' => 'Silver,30 x 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG400', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH DESAIN BULAN A02', 'variasi' => 'Silver,20 x 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG401', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH DESAIN BULAN A02', 'variasi' => 'Silver,10 x 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG402', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH DESAIN BULAN A02', 'variasi' => 'Putih,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG403', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH DESAIN BULAN A02', 'variasi' => 'Putih,30 x 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG404', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH DESAIN BULAN A02', 'variasi' => 'Putih,20 x 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG405', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH DESAIN BULAN A02', 'variasi' => 'Putih,10 x 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG406', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH DESAIN BULAN A02', 'variasi' => 'Hitam,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG407', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH DESAIN BULAN A02', 'variasi' => 'Hitam,30 x 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG408', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH DESAIN BULAN A02', 'variasi' => 'Hitam,20 x 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG409', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH DESAIN BULAN A02', 'variasi' => 'Hitam,10 x 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG410', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH DESAIN BULAN A02', 'variasi' => 'Rose Gold,40 x 40 cm', 'hpp' => 57000],
            ['sku' => 'KLG411', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH DESAIN BULAN A02', 'variasi' => 'Rose Gold,30 x 30 cm', 'hpp' => 31000],
            ['sku' => 'KLG412', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH DESAIN BULAN A02', 'variasi' => 'Rose Gold,20 x 20 cm', 'hpp' => 15500],
            ['sku' => 'KLG413', 'nama_produk' => 'KALIGRAFI ALHAMDULILLAH DESAIN BULAN A02', 'variasi' => 'Rose Gold,10 x 10 cm', 'hpp' => 6000],
            ['sku' => 'KLG414', 'nama_produk' => 'KALIGRAFI BISMILLAH A03', 'variasi' => 'Gold,40 X 30 cm', 'hpp' => 42000],
            ['sku' => 'KLG415', 'nama_produk' => 'KALIGRAFI BISMILLAH A03', 'variasi' => 'Gold,30 X 22,5 cm', 'hpp' => 24500],
            ['sku' => 'KLG416', 'nama_produk' => 'KALIGRAFI BISMILLAH A03', 'variasi' => 'Gold,20 X 15 cm', 'hpp' => 13000],
            ['sku' => 'KLG417', 'nama_produk' => 'KALIGRAFI BISMILLAH A03', 'variasi' => 'Gold,10 X 7,5 cm', 'hpp' => 6000],
            ['sku' => 'KLG418', 'nama_produk' => 'KALIGRAFI BISMILLAH A03', 'variasi' => 'Silver,40 X 30 cm', 'hpp' => 42000],
            ['sku' => 'KLG419', 'nama_produk' => 'KALIGRAFI BISMILLAH A03', 'variasi' => 'Silver,30 X 22,5 cm', 'hpp' => 24500],
            ['sku' => 'KLG420', 'nama_produk' => 'KALIGRAFI BISMILLAH A03', 'variasi' => 'Silver,20 X 15 cm', 'hpp' => 13000],
            ['sku' => 'KLG421', 'nama_produk' => 'KALIGRAFI BISMILLAH A03', 'variasi' => 'Silver,10 X 7,5 cm', 'hpp' => 6000],
            ['sku' => 'KLG422', 'nama_produk' => 'KALIGRAFI BISMILLAH A03', 'variasi' => 'Putih,40 X 30 cm', 'hpp' => 42000],
            ['sku' => 'KLG423', 'nama_produk' => 'KALIGRAFI BISMILLAH A03', 'variasi' => 'Putih,30 X 22,5 cm', 'hpp' => 24500],
            ['sku' => 'KLG424', 'nama_produk' => 'KALIGRAFI BISMILLAH A03', 'variasi' => 'Putih,20 X 15 cm', 'hpp' => 13000],
            ['sku' => 'KLG425', 'nama_produk' => 'KALIGRAFI BISMILLAH A03', 'variasi' => 'Putih,10 X 7,5 cm', 'hpp' => 6000],
            ['sku' => 'KLG426', 'nama_produk' => 'KALIGRAFI BISMILLAH A03', 'variasi' => 'Hitam,40 X 30 cm', 'hpp' => 42000],
            ['sku' => 'KLG427', 'nama_produk' => 'KALIGRAFI BISMILLAH A03', 'variasi' => 'Hitam,30 X 22,5 cm', 'hpp' => 24500],
            ['sku' => 'KLG428', 'nama_produk' => 'KALIGRAFI BISMILLAH A03', 'variasi' => 'Hitam,20 X 15 cm', 'hpp' => 13000],
            ['sku' => 'KLG429', 'nama_produk' => 'KALIGRAFI BISMILLAH A03', 'variasi' => 'Hitam,10 X 7,5 cm', 'hpp' => 6000],
            ['sku' => 'KLG430', 'nama_produk' => 'KALIGRAFI BISMILLAH A03', 'variasi' => 'Rose Gold,40 X 30 cm', 'hpp' => 42000],
            ['sku' => 'KLG431', 'nama_produk' => 'KALIGRAFI BISMILLAH A03', 'variasi' => 'Rose Gold,30 X 22,5 cm', 'hpp' => 24500],
            ['sku' => 'KLG432', 'nama_produk' => 'KALIGRAFI BISMILLAH A03', 'variasi' => 'Rose Gold,20 X 15 cm', 'hpp' => 13000],
            ['sku' => 'KLG433', 'nama_produk' => 'KALIGRAFI BISMILLAH A03', 'variasi' => 'Rose Gold,10 X 7,5 cm', 'hpp' => 6000],
            ['sku' => 'KLG434', 'nama_produk' => 'KUFIC RAMADAN MUBARAK', 'variasi' => 'GOLD', 'hpp' => 17000],
            ['sku' => 'KLG435', 'nama_produk' => 'KUFIC RAMADAN MUBARAK', 'variasi' => 'SILVER', 'hpp' => 17000],
            ['sku' => 'KLG436', 'nama_produk' => 'KUFIC RAMADAN MUBARAK', 'variasi' => 'HITAM', 'hpp' => 17000],
            ['sku' => 'KLG437', 'nama_produk' => 'KUFIC RAMADAN MUBARAK', 'variasi' => 'ROSE GOLD', 'hpp' => 17000],
        ];

        DB::transaction(function () use ($data, $kategori) {

            /*
             * 1. Cek duplicate SKU di dalam data seeder.
             * Jika ada duplicate di file seeder, batalkan semuanya.
             */
            $skuSeeder = collect($data)->pluck('sku');

            $duplicateSeeder = $skuSeeder
                ->duplicates()
                ->unique()
                ->values();

            if ($duplicateSeeder->isNotEmpty()) {
                throw new RuntimeException(
                    'SKU duplicate di data seeder: '.
                    $duplicateSeeder->implode(', ')
                );
            }

            /*
             * 2. Insert / update berdasarkan SKU.
             *
             * SKU sudah ada  -> update / replace
             * SKU belum ada  -> create
             */
            foreach ($data as $item) {

                Produk::updateOrCreate(
                    [
                        'sku' => $item['sku'],
                    ],
                    [
                        'nama_produk' => $item['nama_produk'],
                        'variasi' => $item['variasi'],
                        'hpp' => $item['hpp'],
                        'kategori_id' => $kategori->id,
                    ]
                );
            }

        });
    }
}
